### ISSUE TITLE
Fehler beim sunflower-Block "letzte Beiträge"

### ISSUE THREAD

**Issue by florianbieser** [verdigado/sunflower#357]
Beim Bearbeiten einer Seite mit dem sunflower-Block "letzte Beiträge" wird dieser Block mit der Meldung "In diesem Block ist ein Fehler aufgetreten und eine Vorschau ist nicht möglich." angezeigt, was auch die Bearbeitung der Block-Einstellungen verhindert.

Wenn ich in den Code-Editor wechsle und dann zurück in den virtuellen Editor, funktioniert alles.

**Comment by Benjy04** [comment]
Das selbe bei dem Kalender-Block.

**Comment by Drakemaster** [comment]
Hab das gleiche Problem. Besteht so wie ich das sehe seit dem Update auf Sunflower 1.7.1

**Comment by markusdanieli** [comment]
Hallo,

Wenn ich den Block "Neueste Beiträge (Sunflower)" in eine Seite einfüge, wird mir folgende Meldung angezeigt: "In diesem Block ist ein Fehler aufgetreten und eine Vorschau ist nicht möglich".
Auch ist eine Bearbeitung der Block-Einstellungen nicht möglich.
Theme Version: 1.8.3

Der Fehler scheint offensichtlich schon länger vorzuliegen, gibt es hierzu bereits eine Lösung?

Viele Grüße
Markus

**Comment by cubehrends** [comment]
Gleiches Problem:
![image](https://user-images.githubusercontent.com/19872314/224278088-9b938211-b0fb-4eb4-a0b4-2a2c9e71c12a.png)

In der **/themes/sunflower/build/index.js** bekommt **return wp.data.select("core").getEntityRecords("taxonomy", "category").forEach((e=>{  t.push(e.slug)  }** einen NULL-Wert übergeben.

Da der Bug nun schon seit 9 Monaten besteht, wäre jetzt der perfekte Zeitpunkt um einen Fix zu gebären, Tom ;)

**Comment by markusdanieli** [comment]
Hallo, mit der Version 2.0.3 sieht es gut aus. Vielen Dank
