### ISSUE TITLE
Korrupte Termine bei gleichem Titel 

### ISSUE THREAD

**Issue by softmetz** [verdigado/sunflower#370]
Wenn im relevanten Zeitraum zwei Termine mit identischem Titel (z.B. Vorstandssitzung) importiert werden, werden bei einem der Termine die Angaben für Datum und Uhrzeit entfernt und der Termin kommt nicht mehr zur Ansicht.

Ein Workaround ist, den Termintitel zu individualisieren (z.B. Vorstandssitzung am X.Y.Z). Ein erneuter Import ist aber erst möglich, wenn die alten Termine gelöscht wurden. Die Termin-URL wird generell korrekt mit `-X` ergänzt.

Bisher habe ich das Problem nur bei Terminen im selben Kalender beobachtet, kann aber nicht ausschließen, dass es auch bei Terminen aus mehreren Kalendern zu Kollisionen kommt.

**Comment by codeispoetry** [comment]
Hast Du eine URL für mich, von der aus ihr Eure Termine importiert?

**Comment by softmetz** [comment]
Konkret aufgefallen war es mir bei dieser hier:

https://wolke.netzbegruenung.de/remote.php/dav/public-calendars/GLdpo7e5NYbMqXti?export

**Comment by albig** [comment]
Ich habe das jetzt mit verschiedenen Terminen versucht nachzuvollziehen und war nicht erfolgreich. 

Getestet hab ich mit der aktuellen Nextcloud 28.0.2 und Sunflower 2.0.7.

Ich gehe deshalb davon aus, dass der Bug behoben ist. Wenn es neue Anhaltspunkte gibt, bitte neues Issue öffnen.
