### ISSUE TITLE
"Neueste Beiträge" + YouTube-Einbettung macht Startseite kaputt

### ISSUE THREAD

**Issue by leo-ger** [verdigado/sunflower#382]
"Neueste Beiträge"-Element verhindert das Laden aller nachfolgenden Elemente der Startseite, wenn zudem ein YouTube-Video über die Standard WordPress-Funktion eingebettet wird (vielleicht auch mit anderen Einbettungen, habe es nur mit YouTube getestet/herausgefunden). Wir nutzen zudem Embed Privacy. Wenn ich das "Neueste Einträge"-Element oder die Einbettung entferne, sieht die Startseite ganz normal aus, mit beiden zusammen werden alle Elemente nach dem "Neueste Beiträge"-Element allerdings nicht mehr geladen. Zudem wird nur ein (der erste) Beitrag angezeigt.

Sunflower Version 1.8.1
WordPress Version 6.1.1
Potentiell zusammenhängende Plugins: Embed Privacy

**Comment by albig** [comment]
Ich kann das nicht nachvollziehen. Vielleicht weil zu viel Zeit vergangen ist?

* Sunflower: 2.0.2
* WordPress: 6.4.1
* Embed Privacy: 1.8.1

Seite mit Block (egal in welcher Reihenfolge)

* `wp:sunflower/latest-posts`
* `wp:embed` mit YouTube-Video

**Comment by leo-ger** [comment]
Ja, das Problem scheint nicht mehr zu existieren, vielleicht durch Update von Embed Privacy oder WP oder Sunflower irgendwann behoben 🤷 

Dennoch vielen Dank fürs ansehen!

**Comment by albig** [comment]
Danke für das Feedback. Da hat aussitzen mal geholfen ;-)
