### ISSUE TITLE
Kontaktformular: Reply-To-Header

### ISSUE THREAD

**Issue by b90g** [verdigado/sunflower#383]
Besteht die Möglichkeit beim versenden des Kontaktformulars den Reply-To Header zu setzen? Dann Antwortet zB unser Ticketsystem dahin.

Danke.

**Comment by codeispoetry** [comment]
Man kann das in einem Childtheme in der Datei functions/contact-form in der Zeile 27 mit wp_mail ändern.  Direkt im WordPress-Backend kann man das leider nicht einstellen. Da kann man die Absender-Sender nur festlegen, indem man die Admin-E-Mail-Adresse ändert.

**Comment by ErwinBehner** [comment]
Oder ein Plugin z.B. Contact Form 7 verwenden.

**Comment by b90g** [comment]
https://stackoverflow.com/questions/62899683/set-reply-to-address-in-wp-mail-header#62900959

ich fänds schon nice, wenn das upstream aus dem sunflower theme kommen würde, niemand schreibt seine WordPress-Versandadresse an oder?

**Comment by codeispoetry** [comment]
Ohne reply-to Header wird die Absender-Adresse genommen. Und die ist ja die Admin-E-Mail-Adresse. Oder verstehe ich Dein Anliegen falsch?

**Comment by b90g** [comment]
Also wenn ich ein Kontaktformular ausfülle mit der Emailadresse: anfrage@kunde.de
Bekommen wir eine Email von wordpress@webseite.de

Unser Ticketsystem und vielleicht auch einige Autoresponder senden eine Eingangsbestätigung.

Ziel wäre jetzt dass durch einen Reply-ToHeader gesetzt auf anfrage@kunde.de die Eingangsbestätigung eben nicht an die From Adresse wordpress@webseite.de gesendet wird, die sowieso nur eine Send-Only-Adresse ist.

Und auch wenn man kein Auto-Responder hat man ja beim Antworten automatisch die wordpress@webseite.de Adresse drin die man händisch ersetzten muss.

**Comment by codeispoetry** [comment]
Ah, jetzt habe ich verstanden. Die Mail soll als reply-to-Header von der Nutzerin eingetragene E-Mail-Adresse anführen. Ja, das baue ich ein.

**Comment by albig** [comment]
Das Feature wurde mit https://github.com/verdigado/sunflower/commit/b77ba7e75fe3a728dee83d0f4e8e0f2120a7efc3 umgesetzt.
