### ISSUE TITLE
Kontrastfehler in der Vorlage Nächste Termine

### ISSUE THREAD

**Issue by ralfputz** [verdigado/sunflower#385]
![grafik](https://user-images.githubusercontent.com/121506671/215534701-0ed9c285-13cc-4fa0-b041-1a55c1bce42b.png)

Auf dem grünen Button ist die Beschriftung "Alle Termine" nur bei Mouseover lesbar.

**Comment by albig** [comment]
Das scheint spätestens mit Sunflower 2.0.0 behoben zu sein.
