### ISSUE TITLE
Import Musterbilder funktioniert nicht

### ISSUE THREAD

**Issue by markusdanieli** [verdigado/sunflower#387]
Hallo,
bin gerade dabei mich mit dem neuen Theme auseinanderzusetzen.
Beim Import der Musterbilder kommt bei mir die Meldung: "Es wurden 0 Bilder importiert" und es sind auch keine in der Mediathek.
Ich muss allerdings gestehen, dass ich den Hinweis "Der Import kann einige Minuten dauern. Bitte warte so lange, und klicke nirgendwo hin." nicht geshen hatte und tatsächlich woanders hingeklickt hatte...
Könnt Ihr mir weiterhelfen?
Danke und Gruß
Markus

**Comment by albig** [comment]
Hallo Markus,

ist ja schon eine Weile her. Theoretisch kannst Du den Import ja wiederholen. Hattest Du das gemacht?

Aktuell liegen da 6 Bilder. Zu lange sollte das nicht dauern.

**Comment by markusdanieli** [comment]
Hallo, ja, hatte ich schon mehrmals versucht, es kommt aber immer die Meldung "Es wurden 0 Bilder importiert...", auch bei der neuen Version 2.0.3, ist jetzt aber auch nicht mehr so wichtig... Gruß Markus

**Comment by albig** [comment]
Danke für das Feedback. Dann muss ich doch mal näher rein schauen.

**Comment by albig** [comment]
Der Import funktioniert grundsätzlich. Die Bilder werden direkt von https://sunflower-theme.de mit der PHP-Funktion `file_get_contents()` heruntergeladen.

Welche PHP-Version nutzt Du @markusdanieli? Klappt denn das automatische Update des Sunflower Themes und von WordPress-Plugins?

**Comment by markusdanieli** [comment]
PHP-Version 8.1, Updates von Sunflower oder Plugins funktionieren problemlos.
(zur Info, die Webseite ist mit einem Passwort über htaccess abgesichert, vielleicht liegt es daran)

**Comment by albig** [comment]
Mit der .htaccess schützt Du ja vermutlich deine Seite von außen. Selbst kann sie aber Verbindungen z.B. zu sunflower-theme.de aufbauen. Sonst würdest Du auch keine Updates bekommen. Mmh. Bin ich grad ratlos.

**Comment by albig** [comment]
Ich schließe das Ticket, da es offenbar kein grundsätzliches Problem ist.
