### ISSUE TITLE
im Block Neueste Beiträge fehlen Funktionen

### ISSUE THREAD

**Issue by b90g** [verdigado/sunflower#390]
Ist es möglich den Sunflower Neueste Beiträge Block um die Funktionen des standardisierten WordPress Neueste Beiträge Block zu erweitern?

Block Einstellungen von `Neueste Beiträge` aus WordPress:

![grafik](https://user-images.githubusercontent.com/63392812/227133315-cf92c5a3-0189-4e63-9e52-1401c25a875b.png)

Blockeinstellungen von `Neueste Beiträge (Sunflower):
![grafik](https://user-images.githubusercontent.com/63392812/227133443-d7130032-229d-49e5-a17a-82ebbc229c4d.png)

**Comment by albig** [comment]
Man kann die Features nicht erben, sondern muss sie einzeln nachimplementierne. Teilweise ist das jetzt schon geschehen. Bei weiteren Wünschen bitte separate Issues anlegen.
