### ISSUE TITLE
ICS Export kürzt Texte

### ISSUE THREAD

**Issue by b90g** [verdigado/sunflower#394]
https://chatbegruenung.de/channel/sunflower-wordpress?msg=oh6Zi4bnpS83E99Yx

Anwender*innen haben festgestellt dass die Beschreibungstexte der Events beim ICS Export gekürzt werden.

**Comment by albig** [comment]
Ich vermute, es liegt hier dran: https://github.com/verdigado/sunflower/blob/main/functions/ical.php#L79

Hier wird für das `description` Feld der Auszug in der "üblichen" Länge geholt, statt des vollen Textes. Die "übliche Länge" beträgt nur 30 Wörter. Das kann unter `Sunflower -> Einstellungen -> Layout -> "Anzahl der Wörter im Vorschautext"` angepasst werden.

Für ICS macht das aber keinen Sinn. Hier sollte der Text ungekürzt ausgegeben werden.
