### ISSUE TITLE
ICS Ortsdatenimport / Anzeige in Karte

### ISSUE THREAD

**Issue by Arcturpartner** [verdigado/sunflower#395]
Beim Import der iCal-Daten aus einem Wolkekalender in die Terminverwaltung wird die Map für die Ortsangaben nicht aktiviert/angezeigt. Es besteht auch keine Möglichkeit nachträglich die Kartendaten zu laden bzw. anzeigen zu lassen. Es wäre sehr wichtig, dass diese Funktion ermöglicht wird. Ansonsten macht das ganze Konzept, Pflege der Termine in der Wolke und abonnieren in der Sunflower-Terminverwaltung keinen Sinn!

**Comment by albig** [comment]
Hier gibt es sicherlich Optimierungspotential. Tom hatte das hier beschrieben: https://sunflower-theme.de/documentation/events/#geodaten

* beim Import via ICS werden die Ortsangaben über Nominatim geo-referenziert und das Ergebnis gespeichert.
* es werden pro Import-Durchlauf nur maximal drei Orte neu geo-referenziert
* Fehlerhafte Geo-Referenzierungen lassen sich über die Sunflower-Einstellungen -> Termine -> Korrektur der Marker auf Landkarten von importierten Terminen

Verbesserung von Code und Dokumentation herzlich willkommen. Und gute Vorschläge natürlich auch.

**Comment by albig** [comment]
Dokumentation wurde ergänzt: https://sunflower-theme.de/documentation/events/#geokodierung-der-veranstaltungsorte
