### ISSUE TITLE
Fehler: E-Mails werden NICHT verschleiert dargestellt

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#402]
Mit dem [PageScanner](https://encoder.till.im/scanner) ist uns aufgefallen, dass die Emails nicht hinreichend verschleiert werden.

z.B. unser [OV Heidgraben](https://gruene-heidgraben.de/Kontakt): 

"Schreiben Sie uns gerne eine E-Mail an Info@GRUENE-Heidgraben.de oder nutzen Sie das folgende Kontaktformular:"

```
<p>Schreiben Sie uns gerne eine E-Mail an <a href="#" data-unscramble="ed.nebargdieH-ENEURG@ofnI">Info@GRUENE-Heidgraben.de</a> oder nutzen Sie das folgende Kontaktformular:</p>
``` 

Auf unserer [KV Pinneberg-Seite](https://www.gruene-pi.de/kreisverband-pinneberg/kreisgeschaeftsstelle/) nutzen wir das Plugin "[Email Encoder – Protect Email Addresses and Phone Numbers](https://wordpress.org/plugins/email-encoder-bundle/)":

"E-Mail: Kreisverband@gruene-pi.de"

```
E-Mail:</strong> <a href="javascript:;" data-enc-email="xervfireonaq[at]tehrar-cv.qr" class="mail-link" data-wpel-link="ignore"><span id="eeb-767789-764905"></span><script type="text/javascript">document.getElementById("eeb-767789-764905").innerHTML = eval(decodeURIComponent("%27%4b%72%65%69%73%76%65%72%62%61%6e%64%40%67%72%75%65%6e%65%2d%70%69%2e%64%65%27"))</script><noscript>*protected email*</noscript></a></p>
```

**Comment by svenseeberg** [comment]
Ab wann wäre denn eine E-Mail ausreichend verschleiert? Es ist technisch notwendig, dass man für die Darstellung auf der Homepage immer auch gleich den Code mitliefern muss, um eine E-Mail wieder korrekt darzustellen. Mir scheint der Ansatz, die E-Mail überhaupt im Quellcode anders zu kodieren, nicht mehr zeitgemäß.

**Comment by FloJuh** [comment]
Eigentlich hätte die Nutzung eines Plugins (wie Email Encoder) gereicht, aber im Sunflower-Handbuch steht explizit das die E-mail-Adressen verschleiert werden. Daher sollten wir alle möglichen Schutzmaßnahmen übernehmen.

Wir haben tatsächlich Probleme mit Spam-Mail durch die angegebenen Mails bekommen.

Der Code von Email Encoder ist unter der [Gnu GPLv2](http://www.gnu.org/licenses/gpl-2.0.html) Lizenz als [SVN repository](https://plugins.svn.wordpress.org/email-encoder-bundle/) oder [hier](https://plugins.trac.wordpress.org/browser/email-encoder-bundle/) verfügbar.

**Comment by svenseeberg** [comment]
Wenn der Code verfügbar ist, dann können ihn auch Crawler nutzen?

**Comment by FloJuh** [comment]
Einerseits wird die E-Mail als Parameter im JavaScript (ggf. mit Funktionsaufruf) ver- und entschlüsselt mit ROT16 (und ROT5 für Zahlen) und anderseits im Quellcode die Reihenfolge der Zeichen umgekehr und erst bei der Darstellung im Browser mit Hilfe von CSS wieder in die richtige Reihenfolge gebracht. Bei Übernahme des Codes sollte natürlich die Verschiebechiffre verändert werden.
