### ISSUE TITLE
Markenrechtshinweis bei Theme-Aktivierung

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/sunflower#404]
Das Theme sollte per default ein anderes Logo als die Sonnenblume ausliefern. In den Settings sollte ein Häkchen sein, mit dem man die Sonnenblume als Logo aktivieren kann. Bei dem Häkchen sollte folgender Text eingeblendet werden:

> Die in der Designvorlage verwendeten Graphiken sind als beim DPMA eingetragene Marken (u.a. Registernummer 302016209260 und 302016209584) durch das Markenrecht sowie durch Namens- und Kennzeichnungsrechte geschützt. Grundsätzlich bedarf es einer Erlaubnis, die eingetragenen Schutzrechte zu verwenden (Lizenz). Die Lizenz für Gliederungen ist beschränkt auf ihre Gebiete – digital unbeschränkt – und unbefristet bis zu einem Widerruf. Gebietsverbänden ist es erlaubt, Lizenzen zum Zweck der eigenen Präsentation auch Kandidat*innen  mit der Einschränkung einzuräumen, dass der Anschein eigene Meinungen und Äußerungen seien Positionen des Bundesverbandes oder anderer Gebietsverbände vermieden werden muss. Auch hier besteht ein Widerrufsvorbehalt zugunsten des Bundesverbandes.

**Comment by georgloesel** [comment]
Basierend auf eine Anfrage via Instagram kam die Frage nach Nutzungsbedingungen durch Privatpersonen auf. 
Justiziar der BGS stellt klar dass nur Einzelpersonen mit Mandat der Partei ( z.B. Kandidierende)  das Logo nutzen dürfen.

Zitat: 
`Nach Rücksprache soll es so sein, dass das Sunflower Theme nicht Einzelpersonen offenstehen soll. Ausnahme davon sind Kandidat*innen. Benutzen die das Theme? Wenn nein, prima. Wenn ja, dann müssen wir das bspw. durch die Frage "Bist du Kandidat*in" abfragen (verbunden mit dem Hinweis, dass ansonsten eine unlizenzierte Nutzung erfolgt) und bei Antwort "ja", lassen wir es dann zu.`

Die Texte im Theme müssen dahingehend nochmal überprüft werden.

**Comment by albig** [comment]
Closed, da neue Anforderung in Ticket #645 bearbeitet wird.
