### ISSUE TITLE
Hintergrundfarbe von Blöcken wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by gruenenf** [verdigado/sunflower#427]
Die Hintergrundfarben von Blöcken lässt sich leider in der Version 2.0.1. nicht mehr ändern, bzw. die Anpassungen werden nicht angekommen. 
<img width="1314" alt="Bildschirmfoto 2023-11-06 um 16 10 09" src="https://github.com/verdigado/sunflower/assets/99408805/f0d16f2f-c376-43f4-beb7-019d7494f7cb">
<img width="1424" alt="Bildschirmfoto 2023-11-06 um 16 13 08" src="https://github.com/verdigado/sunflower/assets/99408805/1b225612-fe53-4ad5-99d2-6133cf7373af">

Vielen Dank Euch für den Einsatz!

**Comment by albig** [comment]
Kurios. Kann ich zwar nicht erklären, aber bestätigen. Bei `klee-700`, `black`, Verläufen und eigene Farben geht es. Aber nicht bei den anderen, vorgegebenen Farben.

**Comment by HueHa-v** [comment]
![2023-11-09 16 33 17 localhost 3658d575ab12](https://github.com/verdigado/sunflower/assets/140697096/04e82211-d7b7-4fc8-9be3-8097745faeae)
![2023-11-09 16 32 52 localhost 00da143eb3bf](https://github.com/verdigado/sunflower/assets/140697096/a75cd49a-da08-48bd-b037-3072dc765210)
passt noch nicht ganz. Ich schau morgen weiter

**Comment by albig** [comment]
Hast Du das CSS neu gebaut nach dem auschecken? Also `npm run compile:build`?

**Comment by gruenenf** [comment]
Bei Gray - #EFF2ED funktioniert es bei uns leider noch nicht - mögt ihr das noch einmal prüfen? Vielen Dank

**Comment by albig** [comment]
Stimmt. Sorry, das kommt dann mit 2.0.3 mit.

**Comment by gruenenf** [comment]
Und noch mal ich, 
leider wird nun nicht das ausgewählte Gray #EFF2ED angezeigt, sondern ein dunkleres (ca.) #6b7a80 

LG

**Comment by albig** [comment]
Ja, der Grau-Ton stimmt nicht. Ich frage mich ja, was hier überhaupt grau als Hintergrund-Farbton zu suchen hat. Ich vermute, das ist noch ein Überbleibsel aus dem alten Design. Der neue Styleguide sieht ja nur "Sand" als helle Hintergrundfarbe vor.
Ich lass das aber mal drin und korrigiere im nächsten Release den Farbton.
