### ISSUE TITLE
Sonnenblume im Hauptmenü zu hell

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#428]
Die neue Sonnenblume ist auf einem weißen Hintergrund fast unsichtbar, was die Barrierefreiheit beeinträchtigt.

Es wäre möglicherweise sinnvoll, die Farbe der Sonnenblume im Logo "[B90Gruene_RGB_aufWeiß](https://cms.gruene.de/uploads/images/B90Gruene_RGB_aufWei%C3%9F.jpg)" zu übernehmen. 

Gemäß dem Corporate Design sollte die neue Sonnenblume im Header beim Scrollen die Farben ändern, da verschiedene Hintergründe die Verwendung unterschiedlicher Sonnenblumenfarben erfordern.

Wie bei [gruene.de](https://www.gruene.de/) könnte auch ein Kästchen in grün um die Sonnenblume gesetzt werden.

Neue Sonnenblume:
![image](https://github.com/verdigado/sunflower/assets/122517567/1e54cc98-44aa-491c-bb35-a203e38a3a3e)

Alte Sonnenblume:
![image](https://github.com/verdigado/sunflower/assets/122517567/56e2318c-4ec5-43cb-b4ca-23e3b1781c5c)

Logo:
![B90Gruene_RGB_aufWeiß](https://github.com/verdigado/sunflower/assets/122517567/3932d26f-c41c-45c4-942a-65eac6d2cd1c)

gruene.de:
![image](https://github.com/verdigado/sunflower/assets/122517567/09758158-3ba3-46b6-bfa0-51a5c86eafff)

**Comment by albig** [comment]
Danke für den Hinweis und die Anregungen. Das ist uns auch ins Auge gesprungen, aber zunächst hatten wir keine bessere Lösung. Wir prüfen das noch mal.

**Comment by gumby-man** [comment]
Eigentlich ist die Sonnenblume doch gar nicht zu sehen, weil per CSS auf voll-transparent gesetzt. Ich verstehe nicht ganz warum, aber ist so, oder? Schaut z.B. auf die Sunflower-Homepage (CSS-Regel für .navbar-brand, style.css, ver=2.0.1, ab Zeile 20571, „opacity: 0;“). Ja, diese kleine Sonnenblume doppelt sich ein wenig mit der Sonnenblume im Header direkt darüber (was ja auch zur Startseite verlinkt), aber warum sie dann überhaupt dort eingefügt wird? Als Platzhalter für eine passende Einrückung?

**Comment by gumby-man** [comment]
Ach ja, laut neuer CI gibt es das dunklere Gelb nicht mehr, einzig und allein im Logo, und das soll nur sparsam genutzt werden („nur in der Geschäftsausstattung und für Beschilderungen“, Styleguide z.B. Seite 9 und 48). Eine korrekte Lösung wäre also wahrscheinlich nur analog zu gruene.de eine dunkelgrüne Box drum herum. Für „Social-Media“ wird auch noch die Sonnenblume in „Grashalm“-Grün angeboten, aber da kämen noch Randbedingungen wie Anschnitt und Hintergrundfarbe „Sand“ – wenn man es genau nimmt.

**Comment by gruenenf** [comment]
Die Sonnenblume Grün zu hinterlegen, analog zu grüne.de fände ich persönlich eine ganz schöne Idee.
![Bildschirmfoto 2023-11-08 um 12 14 58](https://github.com/verdigado/sunflower/assets/99408805/a915e43e-0006-42d0-b1f0-f2399e801035)

**Comment by weissgruenbunt** [comment]
Bis zu einer evtl. Änderung kann man folgendes per custom css nutzen:
```css
.navbar-brand img {
    height: 40px;
    position: fixed;
    top: 0px;
    background-color: #005437;
    padding: 7px;
}

@media (min-width: 992px) {
    .navbar-brand img {
        height: 60px;
	padding: 10px;
    }
}
```

**Comment by gruenenf** [comment]
> Bis zu einer evtl. Änderung kann man folgendes per custom css nutzen:
> 
> ```css
> .navbar-brand img {
>     height: 40px;
>     position: fixed;
>     top: 0px;
>     background-color: #005437;
>     padding: 7px;
> }
> 
> @media (min-width: 992px) {
>     .navbar-brand img {
>         height: 60px;
> 	padding: 10px;
>     }
> }
> ```

vielen Dank - das macht sich sehr gut!
