### ISSUE TITLE
aktiver Menüpunkt im Submenu

### ISSUE THREAD

**Issue by morange** [verdigado/sunflower#429]
Im Submenü ist es nicht möglich den aktiven Untermenüpunkt für den Frontend User zu kennzeichen. :/

Hier wäre es hilfreich diesem Punkt eine extra Klasse is-active oder was auch immer zu zuweisen.

Beste Grüße
m.orange

**Comment by gruenenf** [comment]
Moin,
das geht über folgenden custom css Code:

.current-menu-item {
    background: #fff17a;
    color: black;
}

**Comment by morange** [comment]
ah ja, thx

**Comment by albig** [comment]
Das können wir grundsätzlich ja einbauen @HueHa-v . Die Frage ist nur, was hier "richtig" ist. Auf gruene.de wird nichts hervorgehoben. Im TYPO3 Sunflower wird die Textfarbe im Untermenü grün, wie auf der Hauptebene.

**Comment by albig** [comment]
Das sollte mit https://github.com/verdigado/sunflower/pull/471 besser sein. Ansonsten existiert ja auch noch die oben beschriebene Lösung für eigene Lösungen.
Wenn alles nicht passt, bitte neues Issue eröffnen. Am besten mit Screenshot.
