### ISSUE TITLE
PHP Versions Support

### ISSUE THREAD

**Issue by b90g** [verdigado/sunflower#430]
PHP8.2 wurde vor 10 monaten veröffentlicht und sollte unterstützt werden:
https://www.php.net/supported-versions.php

**Comment by albig** [comment]
Wird es doch. Hast Du einen Fehler gefunden?

**Comment by georgloesel** [comment]
@albig  https://chatbegruenung.de/channel/sunflower-wordpress?msg=EGKFCZYEP6Jf4Roaa

**Comment by b90g** [comment]
> Wird es doch. Hast Du einen Fehler gefunden?

als ich fragt ob ich eine Issue draus machen soll gabs nen Daumen nach oben, also hab ich ne Issue draus gemacht, nagut dann mach ichs zu.
