### ISSUE TITLE
Kalender: Enddatum automatisch aus dem Startdatum beziehen

### ISSUE THREAD

**Issue by georgloesel** [verdigado/sunflower#442]
quelle: https://chatbegruenung.de/channel/sunflower-wordpress?msg=8zedYJuakx3jLDSe5

"Anregung an die Programmierer*innen: Könnte man das Enddatum so zeigen dass das vorher eingegebene Startdatum gezeigt wird? das würde Klickarbeit erleichtern.

![image](https://github.com/verdigado/sunflower/assets/14213446/4ddcbcb8-d5ee-48e7-90ad-798a0169725a)

**Comment by albig** [comment]
Der verwendete DateTimePicker ist wohl dieser: https://github.com/xdan/datetimepicker

**Comment by albig** [comment]
behoben in 2.0.3
