### ISSUE TITLE
Aktualisierungshinweis trotz aktueller Version im Backend

### ISSUE THREAD

**Issue by gruenenf** [verdigado/sunflower#450]
Moin,

auch wenn ich die aktuellste Version nutze, wird mir angezeigt, dass es eine aktuellere gibt (und das bereits direkt nach dem Update). Nicht weiter schlimm, aber vielleicht etwas, dass man auch fixen könnte?

![Bildschirmfoto 2023-11-28 um 12 56 36](https://github.com/verdigado/sunflower/assets/99408805/11047fc2-7e0a-44aa-a21a-6fb10523bfe3)

**Comment by albig** [comment]
Das müsste beim nächsten Versions-Check verschwinden. Das passiert aber nur alle 12 Stunden. Ist der Screenshot frisch nach dem Update?

**Comment by gruenenf** [comment]
Ah jo, nun ist es schon verschwunden. Merci!

**Comment by albig** [comment]
Danke für das Feedback. Wie man diesen Versions-Check direkt nach dem Update triggert, weiß ich (noch) nicht. Bist nicht der erste, den das verwirrt hat.
