### ISSUE TITLE
Corporate Design

### ISSUE THREAD

**Issue by Josefwilhelm1** [verdigado/sunflower#459]
Ich denke, dass die Sonnenblume etwas zu hell ist. 
Und das grün im oberen Bereich entspricht nicht dem aktuellen Corporate Design der grünen. Es sollten auch keine 2 verschiedenen Grüntöne verwendet werden.

**Comment by albig** [comment]
Zum Thema Sonnenblume gibt es bereits ein Issue: https://github.com/verdigado/sunflower/issues/428
Die Farbe der Sonnenblume entspricht dem Design-Handbuch für Web. Siehe https://gruene.de/design -> Design-Handbuch -> Seite 11 -> "Sonne" `#fff17a`

Die zwei Grüntöne im Kopf entsprechen den Grüntönen "Tanne" (ganz dunkel) und "Klee". Worauf beziehst Du Dich, dass das nicht dem aktuellen Corporate Design entsprechen soll? Im Styleguide steht zu Web leider nicht viel. Aber zumindest:

_Im Onlinebereich, speziell bei
Social-Media-Formaten, öffnet sich
das Farbspektrum. So kann hier
beispielsweise die Farbe Grashalm
als Hintergrund verwendet werden_

**Comment by Josefwilhelm1** [comment]
Wenn das Alles so im offiziellen Grünen Handbuch zu finden ist, will ich nichts gesagt haben :) Hatte es nur verglichen mit der Seite des Bundesverbandes.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 30.12.23, 11:29 schrieb Alexander Bigga ***@***.***>:

   
  Zum Thema Sonnenblume gibt es bereits ein Issue: #428 Die Farbe der Sonnenblume entspricht dem Design-Handbuch für Web. Siehe https://gruene.de/design -> Design-Handbuch -> Seite 11 -> "Sonne" #fff17a 
  Die zwei Grüntöne im Kopf entsprechen den Grüntönen "Tanne" (ganz dunkel) und "Klee". Worauf beziehst Du Dich, dass das nicht dem aktuellen Corporate Design entsprechen soll? Im Styleguide steht zu Web leider nicht viel. Aber zumindest: 
  Im Onlinebereich, speziell bei Social-Media-Formaten, öffnet sich das Farbspektrum. So kann hier beispielsweise die Farbe Grashalm als Hintergrund verwendet werden

**Comment by DMOEdetc** [comment]
Duplikat von https://github.com/verdigado/sunflower/issues/428
