### ISSUE TITLE
Gallerie Links funtionieren nicht

### ISSUE THREAD

**Issue by MisterMX** [verdigado/sunflower#463]
Links in einem Gallery Block funktionieren nicht, da immer das `data-lightbox` Attribut hinzugefügt wird und dadurch bei jedem Klick sich das Lightbox Popup öffnet.

https://github.com/verdigado/sunflower/blob/fb66d16bfa9445f049003843b54f7c37a499efd0/assets/js/frontend.js#L65

Schritte zum Reproduzieren:

1. Gallerie anlegen
2. Bild in einen Link umwandeln
3. Auf der Website das Bild anklicken. Es öffnet sich nur das Popup, lädt aber nichts.

Das Problem kann "behoben" werden, indem man über F12 das `data-lightbox` Attribut vom Bild entfernt.

**Comment by albig** [comment]
Das gemeinsame Attribut `data-lightbox` ist ja dazu da, damit sich alle Bilder mit diesem Attribut in einer Lightbox öffnen und durchblättern lassen. Soweit, so "normal".

Was meinst du mit "Bild in einen Link" umwandeln? Versteh ich leider nicht :-(

Die "normale" Anwendung ist ja folgende und die funktioniert bei mir problemlos:

![2024-01-04_19-15](https://github.com/verdigado/sunflower/assets/3354500/2f058387-d290-440c-a09d-6b5fdb08e12f)

**Comment by MisterMX** [comment]
Ich möchte die einzelnen Bilder als Links zu anderen Seiten anlegen. Das geht so aber leider nicht, da `data-ligthbox` das Verhalten überschreibt. Es öffnet sich nur das Popup, aber kein Bild wird angezeigt und eine Redirect auf das Linkziel findet auch nicht statt.

**Comment by peerlight** [comment]
Warum wurde das geschlossen bzw. mit welcher Änderung "completed"? 

Das ist doch ein berechtigtes Anliegen, das in anderen Themes auch funktioniert. Zumal dem Bild ein Link zugewiesen werden kann.
