### ISSUE TITLE
Mastodon Teilen-Button auf Einzelseite wird nicht angezeigt

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#464]
![image](https://github.com/verdigado/sunflower/assets/122517567/5207a106-a152-4c06-bf04-734b78ad37e9)

![image](https://github.com/verdigado/sunflower/assets/122517567/0d89183f-f27e-4c59-8fb1-daa92596eca8)

**Comment by albig** [comment]
Ja, das stimmt. Das ist gar nicht so trivial bei Mastodon, weil hier ja nicht einfach ein Link hinzugefügt werden kann. Wann weiß ja nicht, auf welcher Mastodon-Instanz der Besucher ist. Es gibt dafür ne Reihe JavaScript-Lösungen, die man mal prüfen müsste.

**Comment by FloJuh** [comment]
Dann verstehe ich die Aktivierungsmöglichkeit für Mastodon gar nicht. Wenn da momentan gar nichts passieren soll, warum steht dann Mastodon zur Auswahl?

**Comment by albig** [comment]
Das macht an der Stelle momentan keinen Sinn. 

Es gibt ja zwei Möglichkeiten:

1. Implementierung eine Form des "Share on Mastodon"
2. Entfernung der Auswahloption

1. wäre super - es muss nur jemand tun.
2. wäre schnell gemacht, dann wird 1. vermutlich nie
