### ISSUE TITLE
Farbe "Sand" statt Weiß oder Grau

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#465]
>  Ja, der Grau-Ton stimmt nicht. Ich frage mich ja, was hier überhaupt grau als Hintergrund-Farbton zu suchen hat. Ich vermute, das ist noch ein Überbleibsel aus dem alten Design. Der neue Styleguide sieht ja nur "Sand" als helle Hintergrundfarbe vor.
Ich lass das aber mal drin und korrigiere im nächsten Release den Farbton.

_Originally posted by @albig in https://github.com/verdigado/sunflower/issues/427#issuecomment-1830463381_

**Comment by FloJuh** [comment]
Auch hier angemerkt: https://chatbegruenung.de/channel/sunflower-wordpress?msg=mSEW2f5QNPT4BwGTM

**Comment by albig** [comment]
Was ist jetzt hier das Issue? #427 ist doch in #452 gefixt?

**Comment by FloJuh** [comment]
#427 bzw. #452 beziehen sich nur auf Hintergrundfarben von Blöcken. Dieses Issue bezieht sich allgemein auf die Verwendung der Farben weiß (im Hauptmenü, als Hintergrund, als Schriftfarbe) und grau (als Schriftfarbe). Der neue Styleguide sieht nur "Sand" dafür vor.

**Comment by FloJuh** [comment]
Wenn dieses Issue gefixt wird, muss auch #428 gefixt werden. Nach dem Styleguide darf die Sonnenblume nicht auf der Hintergrundfarbe Sand eingesetzt werden (S. 21). Ich finfe

**Comment by FloJuh** [comment]
Die Schriftfarbe im Menü der oberen Seitenleiste sollte auf Weiß oder Sand geändert werden, da der aktuelle Kontrast für eine barrierefreie Nutzung zu gering ist.
![image](https://github.com/verdigado/sunflower/assets/122517567/9d2f08e8-42d5-4f8c-b8a8-1c71811ec51c)
