### ISSUE TITLE
Favicon wird nicht einheitlich angezeigt

### ISSUE THREAD

**Issue by b90g** [verdigado/sunflower#479]
https://chatbegruenung.de/channel/sunflower-wordpress?msg=xjdPDFYvo2Cetkt8d
```
Der Favicon ist ja nur als rel="shortcut icon", nicht als rel="icon" vorhanden (vgl. von Steffen genannte Seite) und auch fehlt die type-Angabe („image/x-icon“). Zuguterletzt könnte Bing natürlich auch mit SVG fremdeln...
```

https://github.com/verdigado/sunflower/blob/2ab15d5ec26e474d9765e236d98a62954a9ff0cf/header.php#L21

**Comment by albig** [comment]
Ein ICO-Format würde ich nicht mehr einbauen wollen. Aber wir können ja überlegen, den `type` und ein PNG-Fallback zu ergänzen.

https://wiki.selfhtml.org/wiki/Favicon#SVG-Favicons

**Comment by b90g** [comment]
gerne, oder eben den ` rel="icon"` teil ich weiß auch nicht.

**Comment by albig** [comment]
Das allein wird nix bringen. Insbesondere den falschen Mime-Type mit dem SVG zu verwenden, dürfte nach hinten los gehen.

**Comment by albig** [comment]
Änderung hat wohl für Bing nicht gereicht. Dann müssen wir als nächstes doch ein `favicon.ico` hinzufügen. Microsoft bekommt das sonst im DOS nicht geladen oder so ;-)

https://answers.microsoft.com/en-us/bing/forum/all/what-are-the-requirements-to-display-favicon-on/236d6598-41e2-483c-9950-aae8714d943c
