### ISSUE TITLE
CSS bei Terminen 

### ISSUE THREAD

**Issue by janschreier** [verdigado/sunflower#486]
Hallo Verdigado Team!

In Version 2.0.6. finde ich folgendes optisch nicht so schön gelöst:

hier bei den Terminen 
https://gruene-aschheim-dornach.de/termine/neujahrsempfang2024/
 
läuft der Text noch etwas weit nach rechts. Oben und links ist mMn. etwas zu viel Platz:
 
![grafik](https://github.com/verdigado/sunflower/assets/2209750/f9112c11-9d48-46d8-ac65-81e7c86bcc23)

ich hätte den Text bündig mit der Überschrift erwartet und dass der Text nicht unter den grünen Kasten rechts läuft.
 
 auch in der mobilen Ansicht  ist das für meinen Geschmack zu viel Whitespace:
 
![grafik](https://github.com/verdigado/sunflower/assets/2209750/ab155dc9-d9e1-4eef-8f8f-66a2501baaf7)

Ist das evtl. ein Fehler auf unserer Seite? Custom CSS haben wir eigentlich keinen. Freue mich über Tipps und stehe für Fragen bereit :)

**Comment by albig** [comment]
Aber das ist jetzt nicht neu mit der Version 2.0.6, oder? Ich schau mir das später mal genauer an.

**Comment by janschreier** [comment]
ich vermute nicht. 2.06 ist unsere erste Version. Aber die Frage stelle ich sonst immer zuerst, wenn ein Bug reinkommt ;)

**Comment by albig** [comment]
Das CSS-Layout ist auf jeden Fall optimierungsfähig. Der grüne Orts-Kasten würde in der aktuellen Version den Text verdecken. Drum ist der vermutlich so weit runtergeschoben worden. Die Überschrift ist extra nach links verschoben. 

Wir können das alles gerne verbessern. Freiwillige vor :-)

Ich lass das offen und werde im nächstes Release das zumindest etwas verbessern.

**Comment by janschreier** [comment]
ich würde die Box aus dem Header rausnehmen und in eine Row mit dem Text selbst schieben. Dass es dann so aussieht:

![grafik](https://github.com/verdigado/sunflower/assets/2209750/b85423e9-8161-4f3e-a2aa-7564e8545ebf)


Bei der Überschrift bin ich mir nicht sicher, ob ich die über die volle breite gehen würde, oder ob die Box quasi ihre eigene Spalte bekommt. ich finde es so, wie im Screenshot dargestellt aber prinzipiell okay. dazu müsste aber das Rendering angepasst werden, weil die Box aktuell Teil des Headers ist.

**Comment by albig** [comment]
Sieht ansprechend aus. Das Page-Rendering muss ich mir anschauen. Könntest Du das Markup / HTML von deinem Screenshot teilen (ev. als Code hier).

**Comment by janschreier** [comment]
Gerne! Hier der ursprüngliche Code:
```html
<article id="post-1353" class="display-single post-1353 sunflower_event type-sunflower_event status-publish hentry">
   <header class="entry-header full-width has-no-post-thumbnail">
      <div class="container">
         <div class="row position-relative">
            <div class="col-12 offset-md-1 text-left col-md-8">
               <h1 class="entry-title">Neujahrsempfang</h1>
            </div>
            <div class="col-md-3 metabox small">
               <div class="text-uppercase weekday">Samstag</div>
               <div class="date mb-2">27.01.2024</div>
               <div class="time mt-2 mb-2">15:00 ‐  17:00 Uhr</div>
               <div class="mt-2 mb-2">Fraktionszimmer<br>Im Kulti<br>Aschheim</div>
               <div><a href="https://gruene-aschheim-dornach.de/?sunflower_event=neujahrsempfang2024&amp;format=ics" class="text-white">Download als ics-Datei</a></div>
            </div>
         </div>
      </div>
   </header>
   <!-- .entry-header -->
   <div class="col-12 col-md-10 offset-md-1">
      <div class="entry-content accordion">
         <div class="metabox-spacer" style="height: 0.5px;"></div>
         <p>Stoppe den Rechtsrutsch. Mit uns! Jetzt ist ein guter Zeitpunkt aufzustehen und sich demokratisch zu engagieren. Am besten natürlich bei Die Grünen 😉</p>
         <p>Interesse? Dann komm (gerne mit der ganzen Familie) zu unserem lockeren Neujahrsempfang und:</p>
         <ul>
            <li>Lern den Grünen Ortsverband kennen</li>
            <li>Triff Deine Gemeinderäte</li>
            <li>Was muss sich in unserer Gemeinde ändern?</li>
            <li>Werde selbst aktiv!</li>
         </ul>
         <p><strong>Wann und Wo?</strong><br>
            Samstag, 27.1. von 15 bis 17 Uhr im Fraktionszimmer im Kulti<br>
            (Seiteneingang Bücherei)
         </p>
      </div>
      <!-- .entry-content -->
      <footer class="entry-footer mt-5">
         <div class="d-flex mt-2 mb-2">
            <div class="social-media-sharers mb-5"><a href="https://twitter.com/intent/tweet?text=Neujahrsempfang&amp;url=https://gruene-aschheim-dornach.de/termine/neujahrsempfang2024/&amp;via=" target="_blank" title="Auf X (Twitter) teilen" class="sharer"><i class="fab fa-x-twitter"></i></a> <i class="fab fa-facebook sharer" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=https://gruene-aschheim-dornach.de/termine/neujahrsempfang2024/', 'sharer', 'width=626,height=436')" title="Share on Facebook "></i> <a href="MAILTO:?subject=Neujahrsempfang&amp;body=https://gruene-aschheim-dornach.de/termine/neujahrsempfang2024/" target="_blank title=" sende="" e-mail"="" class="sharer"><i class="fas fa-envelope"></i></a></div>
            <div>
            </div>
         </div>
      </footer>
      <!-- .entry-footer -->
   </div>
</article>
```

hier der neue Code:
```html
<article id="post-1353" class="display-single post-1353 sunflower_event type-sunflower_event status-publish hentry">
   <header class="entry-header full-width has-no-post-thumbnail">
      <div class="container">
         <div class="row position-relative">
            <div class="col-12 offset-md-1 text-left col-md-8">
               <h1 class="entry-title">Neujahrsempfang</h1>
            </div>
         </div>
      </div>
   </header>
   <!-- .entry-header -->
   <div class="row" style="align-items: flex-start;">
      <div class="col-12 col-md-8">
         <div class="entry-content accordion">
            <div class="metabox-spacer" style="height: 0.5px;"></div>
            <p>Stoppe den Rechtsrutsch. Mit uns! Jetzt ist ein guter Zeitpunkt aufzustehen und sich demokratisch zu engagieren. Am besten natürlich bei Die Grünen 😉</p>
            <p>Interesse? Dann komm (gerne mit der ganzen Familie) zu unserem lockeren Neujahrsempfang und:</p>
            <ul>
               <li>Lern den Grünen Ortsverband kennen</li>
               <li>Triff Deine Gemeinderäte</li>
               <li>Was muss sich in unserer Gemeinde ändern?</li>
               <li>Werde selbst aktiv!</li>
            </ul>
            <p><strong>Wann und Wo?</strong><br>
               Samstag, 27.1. von 15 bis 17 Uhr im Fraktionszimmer im Kulti<br>
               (Seiteneingang Bücherei)
            </p>
         </div>
         <!-- .entry-content -->
         <footer class="entry-footer mt-5">
            <div class="d-flex mt-2 mb-2">
               <div class="social-media-sharers mb-5"><a href="https://twitter.com/intent/tweet?text=Neujahrsempfang&amp;url=https://gruene-aschheim-dornach.de/termine/neujahrsempfang2024/&amp;via=" target="_blank" title="Auf X (Twitter) teilen" class="sharer"><i class="fab fa-x-twitter"></i></a> <i class="fab fa-facebook sharer" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=https://gruene-aschheim-dornach.de/termine/neujahrsempfang2024/', 'sharer', 'width=626,height=436')" title="Share on Facebook "></i> <a href="MAILTO:?subject=Neujahrsempfang&amp;body=https://gruene-aschheim-dornach.de/termine/neujahrsempfang2024/" target="_blank title=" sende="" e-mail"="" class="sharer"><i class="fas fa-envelope"></i></a></div>
               <div>
               </div>
            </div>
         </footer>
         <!-- .entry-footer -->
      </div>
      <div class="col-md-4 metabox small">
         <div class="text-uppercase weekday">Samstag</div>
         <div class="date mb-2">27.01.2024</div>
         <div class="time mt-2 mb-2">15:00 ‐  17:00 Uhr</div>
         <div class="mt-2 mb-2">Fraktionszimmer<br>Im Kulti<br>Aschheim</div>
         <div><a href="https://gruene-aschheim-dornach.de/?sunflower_event=neujahrsempfang2024&amp;format=ics" class="text-white">Download als ics-Datei</a></div>
      </div>
   </div>
</article>

```
zusätzlich hab ich noch folgende CSS Klassenwerte angepasst:
metabox: 
	position:relative; (war absolut)
	top und right entfernt
	
.display-single > .entry-header
	padding: 50px 0 0 0;  (top von 100 auf 50px, bottom von 85px auf 0 geändert)

Ob das Seiteneffekte hat, kann ich nicht sagen. Kenne weder Wordpress noch Bootstrap wirklich gut :)

**Comment by FloJuh** [comment]
Bezieht sich das Issue nicht auch auf Anträge/Beschlüsse [https://sunflower-theme.de/demo/neckarstrasse-wird-fahrradstrasse/](https://sunflower-theme.de/demo/neckarstrasse-wird-fahrradstrasse/)?

**Comment by janschreier** [comment]
Ja, wäre da ähnlich. durch Tag(?) und Datum sieht das aber gerade in Verbindung mit dem Bild mMn. runder aus:
![grafik](https://github.com/verdigado/sunflower/assets/2209750/32c85d45-a56f-4b8f-8fd8-718d9dcc70ae)

Wobei mein Vorschlag optisch auch passen müsste (finde ich  ;)

**Comment by FloJuh** [comment]
Ich finde deinen Vorschlag besser. Auch wenn es bei den Anträgen "runder" aussieht, passt es nicht, dass der Header (Titel, Datum etc.) nicht auf gleicher Höhe mit dem Text ist.

Wenn die Box aus dem Header rausgenommen wird, fände ich des kohärent, wenn der Header zentriert wird. So wie bei den Beiträgen:
![image](https://github.com/verdigado/sunflower/assets/122517567/4800690b-07f6-4c30-a4f6-6e206395aab2)

**Comment by ErwinBehner** [comment]
Wie sieht dies dann mit Beitragsbild aus? Kommt die Box dann neben dem Beitragsbild oder rutscht es dann noch weiter nach unten?

**Comment by albig** [comment]
Ich probier gerade den Vorschlag von @janschreier umzusetzen. Also die Box daneben. Wird aber heute nicht mehr fertig.

**Comment by albig** [comment]
closed with #494

**Comment by janschreier** [comment]
Hallo @albig,

danke für die Übernahme. Wir haben gleich aktualisiert, schaut gut aus :)
In der mittleren Größe (768px) ist der Datumstext zu breit und geht über den Kasten hinaus. 
![grafik](https://github.com/verdigado/sunflower/assets/2209750/c5a55d89-b5be-48d6-ac2c-f4e34c8d48ff)

Eine Möglichkeit wäre es bei von 200% auf 150% zu gehen bei
```
.metabox .date {
  font-size: 150%;
...
```

**Comment by albig** [comment]
Danke @janschreier für das Lob und den Bug in der Tablet-Portrait-Ansicht. Darauf hatte ich tatsächlich nicht geachtet. Na, wird dann im nächsten Bugfix-Release gefixt.

**Comment by FloJuh** [comment]
![image](https://github.com/verdigado/sunflower/assets/122517567/96da9a41-d6c9-4107-9e46-9a7844633f16)
