### ISSUE TITLE
Name im Personen-Block nicht einheitlich

### ISSUE THREAD

**Issue by albig** [verdigado/sunflower#487]
Hinweis aus der Chatbegrünung:

https://chatbegruenung.de/channel/sunflower-wordpress?msg=s2L2vsnQz44HCuA5z

Der Name im Personenblock ist nicht einheitlich gestaltet. Im Markup wird beim ersten Namen die CSS-Klasse `person-name` vergeben, bei den weiteren Namen die Klasse `h4`. Im Frontend sieht das fast identisch aus. Lediglich der Abstand unter dem Namen ist bei `person-name` größer.

Im Backend-Editor stimmt das CSS aber nicht. Bei `person-name` ist der Name fett.

- [ ] einheitliche Verwendung der selben CSS-Klasse
- [ ] Abgleich des Backend-CSS mit dem Frontend-CSS
- [ ] Nutzung von `GrueneType` für den Namen

![2024-01-29_09-59](https://github.com/verdigado/sunflower/assets/3354500/58e1e67b-018f-463b-8a67-e7e35b9dc127)

**Comment by albig** [comment]
@HueHa-v Die Darstellung der mittleren Person mit `GruenType` müsste doch die richtige sein, oder?

**Comment by HueHa-v** [comment]
Ja, die nehmen wir!
