### ISSUE TITLE
Umzug von Urwahl3000 - Termine werden nicht vollständig importiert

### ISSUE THREAD

**Issue by weissgruenbunt** [verdigado/sunflower#498]
Hi,
die Termine werden bei der Umstellung von Urwahl3000 auf sunflower nicht korrekt migriert:

1. WP_Query ist abhängig von Nutzereingabe (Wordpress -> Einstellungen -> Lesen -> Blogseiten zeigen maximal). Bei den Standardeinstellungen (=10) werden auf diese Weise nur die letzten 10 Termine migriert.
Mögliche Lösung: Parameter hinzufügen (Alle = -1 oder einstellbar machen über das Theme mit absolutem Wert, Zeitraum o.Ä.).
```php
// activation.php
...
function sunflower_import_events() {
	$events = new WP_Query(
		array(
			'post_type' => 'termine',
			'posts_per_page' => '-1', // BEISPIEL FÜR ALLE
		)
	);
...
```
2. Das jeweilige Beitragsbild der Termine wird nicht migriert (meta-Wert _thumbnail_id).
Mögliche Lösung: Checken ob Beitragsbild vorhanden und ggf. hinzufügen.
```php
// activation.php
...
function sunflower_import_events() {
	...
        foreach ( $events->posts as $post ) {
                ...
                if($meta['_thumbnail_id'][0]) {
			update_post_meta( $id, '_thumbnail_id', $meta['_thumbnail_id'][0] );
		}
                ...
        ...
...
```

Ich hoffe, dass ich mich verständlich ausgedrückt habe :)

**Comment by albig** [comment]
Danke @weissgruenbunt. Klingt plausibel. Ich hab das Feature noch nie ausprobiert und muss mir mal einen passenden Anwendungsfall suchen.
Ist dein Vorschlag in 2. schon ausreichend? Du kannst natürlich auch einen Pull-Request stellen, wenn Du das eh schon fertig rumliegen hast.
