### ISSUE TITLE
Update Font Aweseome once BlueSky has an icon

### ISSUE THREAD

**Issue by b90g** [verdigado/sunflower#499]
https://github.com/FortAwesome/Font-Awesome/issues/19810

**Comment by albig** [comment]
BlueSky: https://fontawesome.com/icons/bluesky?f=brands&s=solid
Threads: https://fontawesome.com/icons/threads?f=brands&s=solid

Die Icons sind im nächsten Release enthalten durch ein Update von FontAwesome.

**Comment by FloJuh** [comment]
Bluesky-Icon wird aktuell nicht geladen
