### ISSUE TITLE
Barrierefreiheit: Zu niedriger Kontrast beim fokussierten Links im Footer

### ISSUE THREAD

**Issue by sdvg** [verdigado/sunflower#519]
Hier entdeckt: https://sunflower-theme.de/demo/

Wird ein Footer-Link (z.B. "Handbuch") nur fokussiert (ohne Hover), wird eine Schriftfarbe mit sehr niedrigem Kontrast zum Hintergrund verwendet.

<img width="312" alt="Screenshot des Fehlers: Schwarzer Link auf dunkelgrünem Grund" src="https://github.com/verdigado/sunflower/assets/971072/259a1975-aaef-4c6b-a3ec-444551decda5">

**Comment by albig** [comment]
Danke für den Hinweis. Gesehen hatte ich das auch schon. Das sind Überbleibsel vom alten CI.

Mit #520 sollte es dann besser sein.
