### ISSUE TITLE
Emailadressen in Terminen werden falsch entscrambeld

### ISSUE THREAD

**Issue by janschreier** [verdigado/sunflower#526]
Hallo Zusammen,

ich schon wieder - natürlich auch wieder mit einem Termin-Thema ;)

Bei den Terminen klappt das Email-Anti-Spam gerade nicht. Wenn ihr hier:
https://gruene-aschheim-dornach.de/termine/besuch-im-bayerischen-landtag/

auf die Emailadresse klickt, erzeugt er bei mir eine neue Email mit folgendem Empfänger
`vorname ]tod[ nachname ]ta[ gruene-aschheim-dornach ]tod[ de`

also nicht ganz das gewünschte Resultat. Im Editor steht der Link entweder als mailto:vorname.nachname@gruene-aschheim-dornach.de
oder sogar nur die Emailadresse, das Resultat ist jeweils das Gleiche.

hab es in Firefox und Edge (jeweils aktuellste Version) getestet, gleiches Ergebnis. in WP mit Block- und Classic-Editor brachte leider auch das gleiche Ergebnis.

wir sind noch auf 2.0.8, aber an dem Thema habt ihr ja nix geändert, oder?

**Comment by albig** [comment]
Nein. Das Thema haben wir nicht angefasst. Der Termin ist manuell angelegt worden - also nicht über einen ICS-Import, oder?

**Comment by janschreier** [comment]
Genau, gute alte Handarbeit :)

**Comment by albig** [comment]
Nutzt ihr noch andere Plugins um die Emails zu scramblen? Ich kann's grad nicht reproduzieren :-(

**Comment by janschreier** [comment]
an den Teil des Systems komme ich bei uns leider nicht dran.  Ich frag mal unseren Admin. wir sind aktuell leider noch auf PHP 7.4.33. ich melde mich, sobald wir da weiter sind und ich neues weiß

**Comment by albig** [comment]
Ja, wär nett, bevor ich jetzt unnötig suche. Wenn wir das umgehen können, machen wir das natürlich.

**Comment by janschreier** [comment]
so, nach dem Update besteht das Problem immer noch. aber das scheint eher eine Sache von CryptX zu sein. Könntest den Issue also schließen, wenn du es nicht anders siehst. Danke trotzdem wiedermal für die schnelle Hilfe!

**Comment by albig** [comment]
[CryptX](https://de.wordpress.org/plugins/cryptx/) macht vermutlich das selbe, was Sunflower ja auch schon macht: https://sunflower-theme.de/documentation/faq/#die-e-mails-werden-verschleiert-dargestellt-wie-kann-ich-das-abschalten

Vorstellbar, dass sich das in die Quere kommt. Aber das passiert nur bei Inhalten von Terminen? Das müsste doch auch sonst passieren?

**Comment by janschreier** [comment]
ja, das war es. wir haben CryptX jetzt deaktiviert. danke für den Hinweis auf die FAQ!
