### ISSUE TITLE
Kein Icon beim Websitepreview in Whatsapp

### ISSUE THREAD

**Issue by JanDickmann** [verdigado/sunflower#529]
Im Preview auf Whatsapp sollte normalerweise ein Icon angezeigt werden. Das Problem ist, dass im Open Graph Tag, der für das Bild gesetzt wurde, eine svg Datei angegeben wird: 

\<meta property="og:image" content="https://sunflower-theme.de/wp-content/themes/sunflower/assets/img/sunflower.svg" >

Aber Open Graph unterstützt kein svg. ([https://indieweb.org/The-Open-Graph-protocol#Does_not_support_SVG_images](https://indieweb.org/The-Open-Graph-protocol#Does_not_support_SVG_images))

**Comment by albig** [comment]
Danke für den Hinweis. Testen kann man das mit dem Sharing-Debugger von Facebook: https://developers.facebook.com/tools/debug/

gefixt werden muss es hier: https://github.com/verdigado/sunflower/blob/main/template-parts/open-graph.php#L5

Ansonsten ist die Reihenfolge ja
1. hat die Seite / der Beitrag ein Beitragsbild? Dann nimm das.
2. ist die Option "Fallback-Bild für Open-Graph-Tag" gesetzt? Dann nimmt das.
3. Nimm als Fallback `assets/img/sunflower.svg`

Letzteres ist falsch und muss ersetzt werden. Nur durch was?
