### ISSUE TITLE
iCal Termin-Import: Ausnahmen von Wiederholungsevents werden nicht importiert

### ISSUE THREAD

**Issue by amigu** [verdigado/sunflower#537]
In unserem Wolke-Kalender gibt es mehrere Termine mit gleicher UID, was ja bei Wiederholungsevents möglich ist. Der iCal-Import überprüft  `$event->rrule`, um ggf. noch `$event->dtstart` anzuhängen. Dies ist aber bei den fraglichen events in unserem Fall nicht gesetzt, so dass letztlich nur eines der events importiert wird. Möglicherweise liegt es daran, dass diese Termine Ausnahmen von regelmäßigen events sind? 

Vielleicht wäre eine Lösung, `$event->recurrence_id` zu überprüfen statt `$event->rrule`? (die `recurrence_id` ist bei den fraglichen events gesetzt). 

Hier ein aktuelles ICS file, bei dem das Problem auftritt:
[Ss7JqTJi24o5o954-2024-04-03.ics.txt](https://github.com/verdigado/sunflower/files/14858890/Ss7JqTJi24o5o954-2024-04-03.ics.txt)
Es handelt sich um die events mit der UID `7e982519-b4fa-4e5e-81a8-164f8037f2cc`.

**Comment by amigu** [comment]
Workaround: Termine in der Wolke jeweils duplizieren.

**Comment by albig** [comment]
Danke für das Beispiel und die Analyse. Vielleicht ist das ja auch der Grund für https://github.com/verdigado/sunflower/issues/370, was ich nicht reproduzieren konnte.

**Comment by albig** [comment]
Man muss offenbar beides prüfen. `$event->recurrence_id` bzw. `RECURRENCE-ID` ist nur bei Ausnahmen der Wiederholung gesetzt. Dann aber ist `RRULE` nicht vorhanden.

Beispiel:

```
BEGIN:VEVENT
CREATED:20240419T120804Z
LAST-MODIFIED:20240419T120804Z
DTSTAMP:20240419T120804Z
UID:c52b7897-458b-40b1-a1b9-9810bc2e211a
SUMMARY:Test Wiederholung (Juni)
DTSTART;TZID=Europe/Berlin:20240609T081500
DTEND;TZID=Europe/Berlin:20240609T091500
TRANSP:OPAQUE
RECURRENCE-ID;TZID=Europe/Berlin:20240609T081500
SEQUENCE:1
END:VEVENT
```

Referenz: https://icalendar.org/iCalendar-RFC-5545/3-8-4-4-recurrence-id.html
