### ISSUE TITLE
Menüs: Fehlende "Link in einem neuen Tab öffnen" Checkbox

### ISSUE THREAD

**Issue by JanDickmann** [verdigado/sunflower#538]
Bei unserer LV Seite gibt es bei den Menüs diese Checkbox:
![normal-site](https://github.com/verdigado/sunflower/assets/92258731/d145de4c-ce86-4c6c-b8c8-997fe3da03ac)

Bei unserer Mutlisiteinstallation fehlt die Checkbox irgendwie:
![multisite](https://github.com/verdigado/sunflower/assets/92258731/0748d260-2efe-4a64-9f02-95846cc8d572)

Ich kann es mir nicht wirklich erklären. Mache ich was falsch oder ist das ein Bug?

Anmerkung: Beides Sunflower 2.0.9, Wordpress Version 6.5, PHP Version 8.2

**Comment by albig** [comment]
Die Option kann man nur sehen, wenn man sie aktiviert hat. Musst ich auch grad googeln. Hier steht's z.B:

https://docs.presscustomizr.com/article/314-how-to-open-external-menu-links-in-a-new-tab-with-wordpress
