### ISSUE TITLE
Fehler bei Ausrichtung des Blogmoduls

### ISSUE THREAD

**Issue by gruenenf** [verdigado/sunflower#539]
Moin liebes Sunflower Team,

seit dem Update auf PHP 8.2.17 und sunflower Version: 2.0.9 wird das Blog Modul und der RSS-Feed nicht mehr ordentlich dargestellt. Ebenso funktioniert der Menü Hack mit der Grün hinterlegten Sonnenblume aus

https://www.gruene-nf.de/foehr-amrum/
[
<img width="1278" alt="Bildschirmfoto 2024-04-05 um 09 03 15" src="https://github.com/verdigado/sunflower/assets/99408805/f0fa7cb3-9091-4885-b36b-43dee9afb2a8">
](url)

Vielen Dank für die Hilfe,
Karsten

**Comment by albig** [comment]
Kann das sein, dass Ihr grad auf WordPress 6.5 aktualisiert habt? Da hab ich das schon mal gesehen.

**Comment by gruenenf** [comment]
> Kann das sein, dass Ihr grad auf WordPress 6.5 aktualisiert habt? Da hab ich das schon mal gesehen.

Jup, also nutzen auch WordPress 6.5

**Comment by albig** [comment]
Ich denke, es hat was mit WordPress 6.5 zu tun. Sunflower 2.0.9 ist ja schon länger raus. Ich habe diese Woche einen Fall gesehen, den ich aber nicht reproduzieren kann. 

Schau mal auf der Seite in den Code-Editor und entferne bei allen `wp:group` den Teil `"layout":{"type":"constrained"}`. Das hat bei mir geholfen. Woher die die Option kommt, kann dich Dir nicht sagen. Sunflower setzt sie nicht. `twentytwentyfour` aber schon.

**Comment by gruenenf** [comment]
> Ich denke, es hat was mit WordPress 6.5 zu tun. Sunflower 2.0.9 ist ja schon länger raus. Ich habe diese Woche einen Fall gesehen, den ich aber nicht reproduzieren kann.
> 
> Schau mal auf der Seite in den Code-Editor und entferne bei allen `wp:group` den Teil `"layout":{"type":"constrained"}`. Das hat bei mir geholfen. Woher die die Option kommt, kann dich Dir nicht sagen. Sunflower setzt sie nicht. `twentytwentyfour` aber schon.

Jup, das hat das Problem behoben! Vielen Dank

**Comment by albig** [comment]
Freut mich. Dann schließ ich das mal. Wenn mal jemand die Ursache dafür finden würde... Wäre dran interessiert :-)
