### ISSUE TITLE
Temporärer Fontfehler bei Ausklappmenü Pfeil nach unten auf der Startseite - Font!?

### ISSUE THREAD

**Issue by ncws** [verdigado/sunflower#559]
Zeitweise sieht unsere Seite so aus. Normalerweis ist dort, wo hier auf dem Bild das kryptische Zeichen zu sehen ist, ein einfacher Pfeil nach unten.
<img width="933" alt="Bildschirmfoto 2024-04-24 um 20 06 00" src="https://github.com/verdigado/sunflower/assets/15887039/2fb7fe9d-2dfc-4a0f-8dea-991d4d1202a7">
So wie hier auf dem Bild
<img width="933" alt="Bildschirmfoto 2024-04-24 um 20 21 55" src="https://github.com/verdigado/sunflower/assets/15887039/243823fe-97c2-4c9f-8f89-8b8a34cd8faf">

Wenn dieser Fehler auftritt, kann man sich im WP-Admin einloggen und schon ist der Fehler weg. Selbiges gilt, wenn man ein Update des Themes macht. Das habe ich soeben ausgeführt, somit kann man den Fehler jetzt nicht sehen. Für mich schaut es nach einem Berechtigungsfehler aus, der dann bei einem Update wieder korrigiert wird!?

**Comment by ncws** [comment]
Webseite: www.gruene-gifhorn.de

**Comment by albig** [comment]
Ich denke das ist kein Fehler von Sunflower. 

Ihr nutzt WP Optimizer, der alle CSS und JS-Dateien zusammenfasst. Wenn man sich das in der Browser-Konsole (ungecacht) anschaut, sieht man für ca. eine Sekunde den falschen Font. So lange braucht der Server um die CSS-Dateien zusammenzufassen und auszuliefern. Erst danach können die Fonts geholt und angezeigt werden. Wenn alles gecached ist, geht es dann schnell.

Beim Einloggen und nach dem Update des Themes muss der Cache neu aufgebaut werden. Warum zwischendurch mal was schief läuft, kann ich nicht sagen. Liegt aber definitiv nicht am Theme.

**Comment by albig** [comment]
Grundsätzlich macht das WP-Optimize ja bei Euch schon richtig. Wir nutzen das Plugin auch auf manchen Installationen. 

Man müsste sich den Fehlerfall anschauen, was da ggf. schief gelaufen ist. Entweder ist dann die minifizierte CSS-Datei unvollständig oder was auch immer. In der Browser-Console siehst Du, ob und welche Schriften geladen werden bzw. ob es zu Fehlern kam.

**Comment by ncws** [comment]
Ich habe nun umgestellt auf das Plugin Cachify vom pluginkollektiv.org. Die Ladezeiten laut Googles Pageranking waren weder besser noch schlechter als WP-Optimize. Aber vielleicht ist dort über die Jahre zuviel verstellt worden. Das viel schlankere Cachify läuft jetzt in der Grundkonfiguration. Mal schauen, ob dieses Phänomen wieder auftritt.
