### ISSUE TITLE
Fehler bei Nutzung von WordPress 6.5

### ISSUE THREAD

**Issue by dersimoezdag** [verdigado/sunflower#561]
Ab WordPress 6.5 wird bei Gruppen die Klasse nicht mehr außen gesetzt wir vorher:

```<div class="wp-block-group is-layout-constrained wp-block-group-is-layout-constrained">```

sondern eine Ebene weiter innen:

```
<div class="wp-block-group">
   <div class="wp-block-group__inner-container is-layout-constrained wp-block-group-is-layout-constrained">
```

Dadruch findet die Regel 

```
body .is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
    max-width: var(--wp--style--global--content-size);
    margin-left: auto !important;
    margin-right: auto !important;
}
```
hierauf plötzlich Anwendung und verschiebt einige Blöcke blöd. Hierzu weitere infos: https://wordpress.org/support/topic/whats-this-new-frontend-css-ouptut-in-6-5/

**Comment by dersimoezdag** [comment]
Ein Workaround ist das Hinzufügen der Klasse alignfull zu allen Elementen, die sich Verschieben innerhalb von Gruppen:

**Comment by albig** [comment]
Danke für Deine Analyse. Ich vermute das ist der Fehler, den ich jetzt 3-4 Mal gesehen habe (bei einigen hundert Sunflower-Installationen). Ich denke, es ist der selbe Fehler wie in https://github.com/verdigado/sunflower/issues/539 beschrieben.

Mein Workaround war, im Code-Editor bei Gruppen das Attribut `"layout":{"type":"constrained"}` zu entfernen. Das hat unter Sunflower keinen Nutzen, kommt durch Sunflower auch nicht in den Code. Danach war immer Ruhe.

**Comment by albig** [comment]
Du kannst den Editor umschalten in den "Code Editor". Bei den `wp:group` Blöcken stört eben das `"layout":{"type":"constrained"}`, was Du im Sunflower Theme nicht über den Editor entfernen kannst. Eine besser Lösung hab ich aktuell nicht.

![2024-04-26_19-43](https://github.com/verdigado/sunflower/assets/3354500/3a9a7186-9faa-4dea-8e55-c2f03513b5f7)

**Comment by dersimoezdag** [comment]
Ich danke dir, ich probiere es gleich mal aus! Wenn ich mal wieder mehr Zeit habe, suche ich mal weiter nach Lösungen bzw. der Ursache, warum das überhaupt gesetzt wird.

**Comment by albig** [comment]
Vermutlich habe ich das gelöst für das anstehende Update auf Sunflower 2.1.0.
