### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by HueHa-v** [verdigado/sunflower#564]
Features aus 2.1. Dokumentieren
- [x] Logo bestätigen // Term of Use https://github.com/verdigado/sunflower/pull/534
- [x] Button-Highlight ("Mitglied werden") https://github.com/verdigado/sunflower/pull/556
- [x] Textbalken bei Schriften https://github.com/verdigado/sunflower/pull/558
- [x] Header angepasst https://github.com/verdigado/sunflower/pull/543
- [x] RSS-Block Überarbeitet https://github.com/verdigado/sunflower/pull/535
- [x] Vorlage für Kandidierende https://github.com/verdigado/sunflower/pull/557
- [x] Terminblock ("Next events") Übersetzung + Silbentrennung https://github.com/verdigado/sunflower/pull/552
- [x] Update Font-Awesome (Bluesky + Threads)
- [x] Refactor von Blöcken - Handhabung wird intuitiver + Kleinere Funktionen sind dazu gekommen https://github.com/verdigado/sunflower/pull/540
- [x] Neueste Beiträge (Block) - Listenansicht ist neu 
- [x] WordPress Coding und Security Standards https://github.com/verdigado/sunflower/issues/566

Behobene Bugs aus 2.1.
- [x] TAB-Navigation durch Menü (Barrierefreiheit) https://github.com/verdigado/sunflower/pull/550
- [x] Austausch des ICS-Parsers https://github.com/verdigado/sunflower/issues/509
- [x] iCal-Termin-Import: Ausnahmen von Wiederholungsevents werden nicht importiert https://github.com/verdigado/sunflower/pull/551
- [x] PT Sans kursiv https://github.com/verdigado/sunflower/pull/544

"FAQ" in der Doku:
- [x] Menü "in neuem Link öffnen"
- [x] Menü eigene Klasse hinterlegen
- [x] Websitepreview in Whatsapp

**Comment by FloJuh** [comment]
Die Links im Änderungsprotokoll funktionieren nicht.
Außerdem gibt es ein paar Rechtschreibfehler
