### ISSUE TITLE
Vor- und Zurück-Buttons im Carousel - grün statt blau?

### ISSUE THREAD

**Issue by Pietzcker** [verdigado/sunflower#573]
Könnte man die Vor- und Zurück-Buttons im Designelement "Carousel" auf grüne Farbe umstellen?
![image](https://github.com/verdigado/sunflower/assets/15966631/a7980562-255e-4c67-b0e8-85e69c791a75)
Also z. B. auf 0x008939?

Vielen Dank!
Tim

**Comment by HueHa-v** [comment]
Hallo Tim,

Kannst du uns einmal die Seite dazu schicken? 
Meine Vermutung ist, dass ihr ein Block aus dem Plugin "Coblocks" verwendet. Da könnt ihr über die Entwicklertools in den Browsern (Rechtsklick - Untersuchen und dann auf das Element) euch die CSS Klasse der Pfeile raussuchen und über das individuelle CSS Anpassen. 

Das ist kein Element von Sunflower selbst, was ihr verwendet. 

Lieben Gruß,
Hanna

**Comment by Pietzcker** [comment]
Hallo Hanna,

da hast Du sicher recht, das war in der Liste der Inhaltstypen weiter unten :)

Die Seite ist https://blaustein-gruene.de/kommunalwahlen-2024/ - danke für den Tipp mit der CSS-Klasse, mal sehen, wie weit ich komme :)

Herzlichen Dank und viele Grüße,
Tim

**Comment by Pietzcker** [comment]
Okay, ich habe gefunden, wo das definiert ist - laut Inspector in https://blaustein-gruene.de/wp-content/plugins/coblocks/dist/style-coblocks-1.css?ver=3.1.9 - wenn ich die Datei manuell ändere und das background-color-Attribut von #007cba auf #008939 ändere und die Datei speichere, tut sich aber auf der Seite nichts. Der Inspector zeigt weiterhin #007cba an, obwohl die .css-Datei jetzt einen anderen Inhalt hat. Reload (F5/Strg-F5) ändert auch nichts. 

Offensichtlich habe ich da noch einen grundsätzlichen Denkfehler...vielleicht wegen dieses "ver=3.1.9"-Querystrings? Aber wo hätte ich die Änderung machen sollen? Sorry wegen der Anfängerfrage, bin noch nicht so lange mit Wordpress unterwegs...

Danke und viele Grüße
Tim

**Comment by HueHa-v** [comment]
Du kannst CSS über den Customizer des Themes überschrieben. Das nennt sich dann "individuelles CSS". Änderungen in Plugin Dateien gehen dir eh über ein Update verloren. 

`.nav-button__next, .nav-button__prev {
    background-color: #008939;
}`

**Comment by Pietzcker** [comment]
Super, vielen Dank! Sehr schön, wenn die Buttons nicht mehr an eine Partei erinnern, die Blau als Lieblingsfarbe hat 🤢

Ihr seid die Besten!
