### ISSUE TITLE
Nach Update auf Sunflower Themes 2.1.0 nur noch weiße Seite zu sehen

### ISSUE THREAD

**Issue by Dirk-Hoff** [verdigado/sunflower#577]
Hab eben das Update des Sunflower Themes von 2.0.9 auf 2.1.0 gemacht. 
Jetzt sehe ich leider nur noch eine weiße leere Seite. 

Ich hoffe jetzt ist nicht alles futsch....
Ich wäre für Hilfe seeehr dankbar.

Siehe
(https://gruene-lwv-hessen.de/)
 
WordPress Version 6.5.2
PHP Version 8.2

Danke und Grüße

**Comment by albig** [comment]
Danke für die Rückmeldung. Hier scheint auch das Hauptmenü zu fehlen. Unterseiten funktionieren vom Inhalt, oder? Beispiel

https://gruene-lwv-hessen.de/impressum/

**Comment by Dirk-Hoff** [comment]
Die Startseite ist ganz weg.
Und ja, bei den Inhaltsseiten und Beiträgen fehlt der ganze Kopfbereich mit dem Hauptmenü.

Ich hoffe ihr könnt helfen.

**Comment by Pietzcker** [comment]
Bei mir ist auf einer der Seiten ein graues Overlay über dem oberen Teil der Seite, durch den nicht durchgeklickt werden kann: https://blaustein-gruene.de/kommunalwahlen-2024/

Im Site Inspector finde ich kein "schuldiges" Element dafür...

**Comment by albig** [comment]
Danke. Bitte die Issues nicht vermischen.

**Comment by albig** [comment]
Wir haben gerade ein Bugfix Release 2.1.1 veröffentlicht. Sollte sich ebenso automatisch installieren. Bitte gebt dann Rückmeldung, ob sich die o.g. Probleme gelöst haben.

**Comment by ErwinBehner** [comment]
Auch bei mir sind eine Reihe von Seiten weg und zeigen nur noch einen weißen Bildchirm. Die Startseite habe ich jetzt neu erstellt. Bei der KV und den OV-Seiten hoffe ich dass es mir erspart bleibt. Bei den fehlhaften Seiten sind dann auch oben die Menüleiste kaputt.
Es werden eine Reihe von Fehlern ausgespuckt (Hinweis: Ich habe die Pfade gekürzt):
Ein Fehler vom Typ E_ERROR wurde in der Zeile 340 der Datei ../themes/sunflower/functions/events.php verursacht. Fehlermeldung: Uncaught TypeError: sunflower_is_numeric_array(): Argument #1 ($value) must be of type array, string given, called in ../themes/sunflower/functions/latest-posts.php on line 21 and defined in ../themes/sunflower/functions/events.php:340
Stack trace:
#0 ../themes/sunflower/functions/latest-posts.php(21): sunflower_is_numeric_array()
#1 ../themes/sunflower/build/latest-posts/render.php(44): sunflower_get_latest_posts()
#2 ../wp-includes/blocks.php(519): require('...')
#3 ../wp-includes/class-wp-block.php(463): {closure}()
#4 ../wp-includes/blocks.php(1705): WP_Block->render()
#5 ../wp-includes/blocks.php(1743): render_block()
#6 ../wp-includes/class-wp-hook.php(324): do_blocks()
#7 ../wp-includes/plugin.php(205): WP_Hook->apply_filters()
#8 ../wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1865): apply_filters()
#9 ../wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(569): WP_REST_Posts_Controller->prepare_item_for_response()
#10 ../wp-includes/rest-api/class-wp-rest-server.php(1230): WP_REST_Posts_Controller->get_item()
#11 ../wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request()
#12 ../wp-includes/rest-api.php(555): WP_REST_Server->dispatch()
#13 ../wp-includes/rest-api.php(2922): rest_do_request()
#14 [internal function]: rest_preload_api_request()
#15 ../wp-includes/block-editor.php(750): array_reduce()
#16 ../wp-admin/edit-form-blocks.php(77): block_editor_rest_api_preload()
#17 ../wp-admin/post.php(187): require('...')

https://www.gruene-dillingen.de/

**Comment by albig** [comment]
Der Fehler im `next-events` block hab ich auch jetzt gesehen. Du hast hier sicher gefiltert nach Tags? Das könnte schon die Ursache der weißen Seite sein. Mach ich morgen früh.

Die Menüs oben sind mit 2.1.1 wieder da. Die waren weg, wenn man die `header_layout` Einstellung nie angefasst hat. Er hat dann nicht den Default verwendet.

**Comment by ncws** [comment]
Bei uns waren einige ältere Seiten nicht mehr zu sehen oder in einer Art "Mobiler Ansicht" ohne Inhalt
Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 340 der Datei /var/www/web268/html/gruene-gifhorn.de/wp-content/themes/sunflower/functions/events.php verursacht. Fehlermeldung: Uncaught TypeError: sunflower_is_numeric_array(): Argument #1 ($value) must be of type array, string given, called in /var/www/web268/html/gruene-gifhorn.de/wp-content/themes/sunflower/functions/latest-posts.php on line 21 and defined in /var/www/web268/html/gruene-gifhorn.de/wp-content/themes/sunflower/functions/events.php:340
Stack trace:
#0 /var/www/web268/html/gruene-gifhorn.de/wp-content/themes/sunflower/functions/latest-posts.php(21): sunflower_is_numeric_array()
#1 /var/www/web268/html/gruene-gifhorn.de/wp-content/themes/sunflower/build/latest-posts/render.php(44): sunflower_get_latest_posts()
#2 /var/www/web268/html/gruene-gifhorn.de/wp-includes/blocks.php(519): require('...')
#3 /var/www/web268/html/gruene-gifhorn.de/wp-includes/class-wp-block.php(463): {closure}()
#4 /var/www/web268/html/gruene-gifhorn.de/wp-includes/blocks.php(1705): WP_Block->render()
#5 /var/www/web268/html/gruene-gifhorn.de/wp-includes/blocks.php(1743): render_block()
#6 /var/www/web268/html/gruene-gifhorn.de/wp-includes/class-wp-hook.php(324): do_blocks()
#7 /var/www/web268/html/gruene-gifhorn.de/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#8 /var/www/web268/html/gruene-gifhorn.de/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1865): apply_filters()
#9 /var/www/web268/html/gruene-gifhorn.de/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(569): WP_REST_Posts_Controller->prepare_item_for_response()
#10 /var/www/web268/html/gruene-gifhorn.de/wp-includes/rest-api/class-wp-rest-server.php(1230): WP_REST_Posts_Controller->get_item()
#11 /var/www/web268/html/gruene-gifhorn.de/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request()
#12 /var/www/web268/html/gruene-gifhorn.de/wp-includes/rest-api.php(555): WP_REST_Server->dispatch()
#13 /var/www/web268/html/gruene-gifhorn.de/wp-includes/rest-api.php(2922): rest_do_request()
#14 [internal function]: rest_preload_api_request()
#15 /var/www/web268/html/gruene-gifhorn.de/wp-includes/block-editor.php(750): array_reduce()
#16 /var/www/web268/html/gruene-gifhorn.de/wp-admin/edit-form-blocks.php(77): block_editor_rest_api_preload()
#17 /var/www/web268/html/gruene-gifhorn.de/wp-admin/post.php(187): require('...')
#18 {main}
  thrown
  
  Temporäre Lösung: Sunflower Theme gelöscht und die ältere Version wieder installiert:
  https://sunflower-theme.de/updateserver/sunflower-v2.0.9.zip

**Comment by albig** [comment]
Bitte nicht den selben Fehler noch mal melden. Das behebt ihn auch nicht schneller ;-)

**Comment by albig** [comment]
Die Ursache ist folgendes im Code-Editor:
```
<!-- wp:group {"className":"has-sand-background-color has-background"} -->
<div class="wp-block-group has-sand-background-color has-background"><!-- wp:sunflower/latest-posts {"categories":"allgemein,ratsfraktion","title":"Aktuelles"} /--></div>
<!-- /wp:group -->
```

**Comment by gruenenf** [comment]
> Die Ursache ist folgendes im Code-Editor:
> 
> ```
> 
> <div class="wp-block-group has-sand-background-color has-background"></div>
> 
> ```

Ich komme leider auch nach dem Update auf 2.1.1. nicht mehr an unsere Startseite ran, um diese zu bearbeiten und dort etwas im Code zu ändern: 
gruene-nf.de 
Bei gruene-flensburg.de ist die Startseite leider ebenfalls noch immer nicht wieder hergestellt. 

LG

**Comment by ncws** [comment]
Du müsstest von eurem Wordpess-Server eine E-Mail mit dem Betreff "Deine Website hat ein technisches Problem" und einen Link zum Starten des Wiederherstellungsmodus bekommen haben. Damit solltest du in die Wordpress-Admin-Konsole kommen.

**Comment by ncws** [comment]
> Ich komme leider auch nach dem Update auf 2.1.1. nicht mehr an unsere Startseite ran, um diese zu bearbeiten und dort etwas im Code zu ändern:
> gruene-nf.de
> Bei gruene-flensburg.de ist die Startseite leider ebenfalls noch immer nicht wieder hergestellt.

Du müsstest von eurem Wordpess-Server eine E-Mail mit dem Betreff "Deine Website hat ein technisches Problem" und einen Link zum Starten des Wiederherstellungsmodus bekommen haben. Damit solltest du in die Wordpress-Admin-Konsole kommen.

**Comment by albig** [comment]
Auf gruene-flensburg.de läuft jetzt Sunflower 2.1.2 und damit ist die Seite wieder zugänglich.

@Dirk-Hoff bitte gibt eine Rückmeldung, sobald 2.1.2 installiert ist, ob die Startseiten-Probleme gelöst sind.

**Comment by gruenenf** [comment]
Habs auf der gruene-nf Seite geupdatet und funktioniert auch wieder – merci!

**Comment by Dirk-Hoff** [comment]
Leider hat sich nichts geändert.

Die Startseite ist immer noch leer, bis auf den Header. Siehe (https://gruene-lwv-hessen.de/)
Die Beitragsseiten sind auch noch leer, bis auf den Header. Siehe (https://gruene-lwv-hessen.de/aktuelles/beitraege/)
Und das Burgermenü funktioniert auch nicht.

Getestet mit Chrome und Firefox auf Windows und Android. Cookies und Cache gelöscht.

**Comment by albig** [comment]
Komisch. Lässt sich die Startseite bearbeiten oder gibt es dann die Fehlermeldung "Es ist ein kritischer Fehler aufgetreten"? Wenn sie sich bearbeiten lässt, würde mich der Inhalt interessieren. Also auf Code-Editor umschalten und raus kopieren. Und entweder hier rein oder mir per Mail schicken.

Mit dem Browser hat das nix zu tun. Die Inhalte sind einfach nicht auf der Seite.

**Comment by Dirk-Hoff** [comment]
Funktioniert wieder alles!!!

Nachdem ich die Startseite einmal zur Bearbeitung geöffnet habe, ging wieder alles.

Ich danke euch sehr für die schnelle Hilfe! Wirklich toll!

Grüße
Dirk

**Comment by Dirk-Hoff** [comment]
Nein Caching-Plugin.

Ich danke Dir/Euch sehr für die schnelle Hilfe.
Schön zu erleben, dass das System so gut betreut wird.
Bevor sie ganz große Panik aufkam, Ward ihr schon da.

Viele Grüße aus Kassel
Dirk

⁣________________________________
Dirk Hoffmann
0151 233 700 69
***@***.***​
