### ISSUE TITLE
Nach Update auf Sunflower 2.1.0 graues Overlay über einem Teil der Seite

### ISSUE THREAD

**Issue by Pietzcker** [verdigado/sunflower#580]
Bei mir legt sich auf einer der Seiten ein graues Overlay über den oberen Teil der Seite, durch das nicht durchgeklickt werden kann: https://blaustein-gruene.de/kommunalwahlen-2024/

Im Site Inspector finde ich kein "schuldiges" Element dafür...

Andere Seiten scheinen nicht betroffen zu sein, ich finde keinen relevanten Unterschied, an dem es liegen könnte.

Wordpress-Version 6.5.2, PHP 8.2

**Comment by stiglers-eponym** [comment]
Die Ursache ist vermutlich folgende:
in sass/_layout.scss:232 wird das Overlay für die Klasse `sunflower-has-background-dim` definiert und in src/next-events/render.php:20 ist für den next events Block hartkodiert, dass dieser diese Klasse nutzt. Allerdings ist das Overlay absolut positioniert, sodass es nicht über dem next events Block liegt. Der Stil für den next events Block müsste also möglicherweise angepasst werden.

Damit es nicht ganz so schlimm aussieht, kann man das overlay vermutlich im customizer entfernen: `.next-events::before { content: none !important; }`. Allerdings bleibt das Problem, dass der Hintergrund im next events Block zu hell ist. (Das ist ja der Grund, warum dieses Overlay im Layout definiert ist, auch wenn es in diesem Fall nicht an der richtigen Stelle landet.)

**Comment by Pietzcker** [comment]
Das Problem scheint mit Version 2.1.1 behoben zu sein. Wow, vielen Dank! Schneller geht's nicht 🥇

**Comment by albig** [comment]
Die Ursache ist dieses gedimmte Background-Image vom `next-events` block, wie @stiglers-eponym richtig erkannt hat. Das funktioniert(e) nur im `styled_layout`. Alles nicht schön. Jetzt sollte es auch ohne `styled_layout` wieder gehen.

**Comment by Dirk-Hoff** [comment]
Leider ist noch nicht alles gut.

Das Themes hat sich aktualisiert auf 2.1.1
Der Header mit dem Hauptmenü ist wieder da, aber:

- Der Inhalt der Startseite ist immer noch nicht sichtbar, leere Seite mit Header.
- Alle "Beiträge" sind nicht sichtbar, leere Seite mit Header. Die "Seiten" hingegen sind alle da.
- Die Navigation in der mobilen Ansicht mit dem Burgermenü funktioniert nicht.

Ich hoffe ihr bekommt das auch noch hin!
Kann ich irgendwas beitragen, um den Fehler zu finden?
(https://gruene-lwv-hessen.de/)

**Comment by Dirk-Hoff** [comment]
Funktioniert wieder alles!!!

Nachdem ich die Startseite einmal zur Bearbeitung geöffnet habe, ging wieder alles.

Ich danke euch sehr für die schnelle Hilfe! Wirklich toll!

Grüße
Dirk
