### ISSUE TITLE
DateTimeZone Fehler mit 2.1.1

### ISSUE THREAD

**Issue by Jako** [verdigado/sunflower#590]
Hallo, ich weiß nicht, ob dieser Fehler mit der 2.1.2 schon behoben worden ist. In der [Übersicht](https://github.com/verdigado/sunflower/compare/v2.1.1...v2.1.2) hab ich es auf den ersten Blick nicht gesehen. Falls er schon behoben ist, bitte hier einfach abschließen.

```
Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /.../wp-content/themes/sunflower/functions/icalimport.php:35
Stack trace:
#0 /.../wp-content/themes/sunflower/functions/icalimport.php(35): DateTimeZone->__construct()
#1 /.../wp-content/themes/sunflower/functions/icalimport.php(234): sunflower_icalimport()
#2 /.../wp-includes/class-wp-hook.php(324): sunflower_import_icals()
#3 /.../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /.../wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /.../wp-settings.php(695): do_action()
#6 /.../wp-config.php(95): require_once('...')
#7 /.../wp-load.php(50): require_once('...')
#8 /.../wp-login.php(12): require('...')
#9 {main}
thrown
```

**Comment by albig** [comment]
Nein, das ist noch nicht bekannt.

**Comment by albig** [comment]
Wie kann ich das reproduzieren? Ggf. bitte den Link zur ICS-Ressource hier posten oder an support@verdigado.com schicken. Bei mir passiert das nicht.

**Comment by Jako** [comment]
Ok, ich kenne mich mit Internals von Wordpress nicht aus. Woher kommt der Wert aus `get_option( 'timezone_string' )`?

**Comment by albig** [comment]
Einstellung -> Allgemein:

![2024-05-08_13-58](https://github.com/verdigado/sunflower/assets/3354500/d8c494f1-3d01-47e7-90c0-035b2120ea80)

Aber vielleicht brauchen wir an der Stelle einen Default. Bin nicht davon ausgegangen, dass die Option leer sein kann.

**Comment by Jako** [comment]
Vielleicht braucht es dort nur einen sinnvollen Standardwert:
https://developer.wordpress.org/reference/functions/get_option/

**Comment by Jako** [comment]
Bei uns steht da `UTC+2` drin. Ich könnte es auf Berlin stellen, dann wäre der Fehler wohl weg. Das ist dann aber auch nur ein schlechter Workaround.

**Comment by albig** [comment]
Für Dich wär das gefixt. Ich überleg mir mal einen Check. `UTC+2` müsstest Du aber auch zwei Mal im Jahr anpassen, oder? Auch eher unpraktisch.

**Comment by Jako** [comment]
Hab ich auch gerade festgestellt. Ist das ein Standardwert, der beim Einrichten aus Servervariablen genommen wird?

**Comment by albig** [comment]
Das kann sein. Ist das ein shared Hosting? Trotzdem muss Sunflower ja mit so nem Wert auf "irgendwas" zurückfallen. Und sei es GMT.

**Comment by Jako** [comment]
Das ist ein Managed Hosting von hostNET in Bremen. Ich weiß leider nicht mehr, ob ich das Wordpress per Hand eingerichtet habe oder es so ein Autoinstall Server Package war.
