### ISSUE TITLE
Neueste Beiträge Block kann nicht mehr bearbeitet werden

### ISSUE THREAD

**Issue by JanDickmann** [verdigado/sunflower#591]
Hi, wir haben ein Problem mit dem "Neuste Beiträge" Block, möglicherweise durch das Update. Auf 2.0.9 hatten wir das Problem nicht.
Der "Neuste Beiträge" Block wird aktuell im Editor so angezeigt:

![Neuste Beiträge Block](https://github.com/verdigado/sunflower/assets/92258731/dda3ce5d-1ee7-4fae-8d64-46a7a31ee7c2)

Sobald man versucht irgendwas daran zu ändern, also z.B. in der rechten Seitenleiste die Anzahl der angezeigten Elemente verändert, sieht der Block im Editor so aus:

![Neuste Beiträge Block kaputt](https://github.com/verdigado/sunflower/assets/92258731/fb5a6985-b0bb-4e8c-8278-1882874414ed)

und man kann nichts mehr dran verändern, also es werden in der Seitenleiste keine Optionen mehr angezeigt.
Laut meinem Kollegen wird der Block auch auf der Seite nicht mehr richtig angezeigt: "die formatierte Ansicht des Blocks ist weg (keine Ränder mehr oben unten bzw. unter der Headline)".

**Comment by albig** [comment]
Oha. Was für eine PHP-Version nutzt ihr? Kannst Du mal in die Browser-Entwickler-Konsole (F12) schauen, was dort steht? Und schalte mal auf den "Code Editor" im Wordpress und kopier den Teil vom "latest-post" heraus und kopier das mal hier rein. 

Noch weiß ich leider nicht, wie ich das nachvollziehen soll.

**Comment by JanDickmann** [comment]
PHP Version 8.2.18
Das ist die Fehlermeldung aus der Entwickler Konsole:
Error: Objects are not valid as a React child (found: object with keys {error, errorMsg}). If you meant to render a collection of children, use an array instead.
    i https://gruene-saar.de/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10
    l https://gruene-saar.de/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10
    toArray https://gruene-saar.de/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10
    A https://gruene-saar.de/wp-includes/js/dist/element.min.js?ver=cb762d190aebbec25b27:9
    wt https://gruene-saar.de/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    js https://gruene-saar.de/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    wl https://gruene-saar.de/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    bl https://gruene-saar.de/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    yl https://gruene-saar.de/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    il https://gruene-saar.de/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    ol https://gruene-saar.de/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    v https://gruene-saar.de/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10
    ce https://gruene-saar.de/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10
    c moz-extension://cd637ccc-6645-408e-8b22-52dd65b2257b/dist/ruffle.js?id=89772302635:19
    c moz-extension://cd637ccc-6645-408e-8b22-52dd65b2257b/dist/ruffle.js?id=89772302635:19
    d moz-extension://cd637ccc-6645-408e-8b22-52dd65b2257b/dist/ruffle.js?id=89772302635:19

Im Code Editor ist der Block einfach nur:

**Comment by albig** [comment]
Danke. Noch führt es mich auf keine Idee. 

Einen Fehler hab ich bei Euch gesehen, der aber mit dem o.g. keinen Einfluss haben sollte. Bei Euch scheint das Zoomlevel für die Karten auf `leer` gestellt zu sein. Das müsste das Theme unterbinden, tut es aber nicht. Stellt da mal bitte `11` ein, was der Default ist:

![2024-05-09_10-54](https://github.com/verdigado/sunflower/assets/3354500/35a1bce7-ae36-46bc-859e-1c62fce5f44a)

Ihr nutzt WP Optimize. Der fasst JavaScript-Dateien ja zusammen. Das sollte er nur fürs Frontend machen. Wenn das JavaScript einen Fehler enthält (wie beim fehlenden Zoom-Wert) kann sonst was passieren.

1. Tragt den Zoomwert ein --> schaut ob der Fehler weg ist.
2. Wenn nicht, deaktiviert WP Optimize und schaut ob sich was verändert.

Wenn WP Optimize "schuld" ist, schauen wir dann weiter in die Richtung.

**Comment by JanDickmann** [comment]
Der Zoomwert `11` war tatsächlich eingetragen.

Ich hab mal WP Optimize deaktiviert aber keine direkte Veränderung feststellen können, also das Problem besteht weiterhin.

**Comment by albig** [comment]
Ich bin leider grad ratlos. Was passiert, wenn ihr auf einer neuen, leeren Seite nur den Sunflower Block "Letzte Beiträge" einfügt? Geht das auch nicht?

**Comment by JanDickmann** [comment]
Ne, das Problem bleibt bestehen, auch bei einer neuen Seite. Mir fällt gerade auf, dass es auch genauso beim Nächste Termine Block passiert.

**Comment by albig** [comment]
Wenn die Meldung kommt, steht vermutlich etwas in der Browser-Entwicklerkonsole dazu. Das wäre interessant zu erfahren. Das ist auf keinen Fall "normal".
