### ISSUE TITLE
Termine lassen sich im ics-Format nicht abonnieren

### ISSUE THREAD

**Issue by ErwinBehner** [verdigado/sunflower#592]
Der Link "Kalender im ics-Format" bei der Terminübersicht funktioniert nicht mehr. Es kommt die Fehlermeldung: "Der Link, dem du gefolgt bist, ist abgelaufen."

**Comment by albig** [comment]
Tatsache. Danke dir. Der ICS-Link am Termin funktioniert. In der Übersicht aber nicht.
