### ISSUE TITLE
 Custom Logo als Favicon

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#597]
Bei Verwendung eines Custom Logos wird es nicht als Favicon (also Website Icon) gesetzt.

Folgende Einstellungsmöglichkeit ist beim Sunflower-Theme deaktiviert:
![image](https://github.com/verdigado/sunflower/assets/122517567/1783d901-6a99-4e1f-b06b-64a24c9a5c71)
 
Eigentlich wird die Sonnenblume automatisch als Favicon gesetzt. Jetzt müssen dafür aber die Nutzungsbedingungen akzeptiert werden, sodass bei Ablehnung der Nutzungsbedingungen gar kein Favicon gesetzt wird.

**Comment by albig** [comment]
Seit WordPress 6.5 kann man das Favicon ("Website-Icon") unter Einstellungen -> Allgemein setzen. Das Feature ist hier beschrieben https://core.trac.wordpress.org/ticket/54370 und mit diesem Commit umgesetzt: https://github.com/WordPress/wordpress-develop/commit/35feae5c75169ce83620091e9849ee0fdec8bd9e

In Zusammenhang mit Sunflower gibt es zwei Szenarien:

1. Nutzungsbedingungen _nicht_ akzeptiert: Website-Icon ist auswählbar und wird als Favicon verwendet.
2. Nutzungsbedingunge akzeptiert: Website-Icon ist mit der Sonnenblume vorbelegt. Ein Entfernen oder eine Austausch ist zunächst möglich, wird nach dem Speichern aber verworfen und wieder die Sonnenblume gesetzt.

![2024-05-14_11-12](https://github.com/verdigado/sunflower/assets/3354500/d313e8e1-fd08-4d89-96c9-5a7695a641a7)

Das Logo automatisch als Favicon zu verwenden, würde ich nicht automatisch machen. Das kann komplett schief aussehen. Entsprechend sehe ich aktuell hier keinen Sunflower-Bug sondern eher ein Dokumentations-Defizit, dass man Logo und Website-Icon an unterschiedlichen Stellen konfigurieren muss.

**Comment by FloJuh** [comment]
Danke! Das habe ich gar nicht mitbekommen. Ich hätte nicht gedacht, dass WordPress so etwas ändert.

**Comment by albig** [comment]
Im Theme Customizer  hatte sunflower die Option "website icon" aktiv entfernt. Da sie jetzt unter "Einstellungen -> Allgemein" unter WordPress 6.5 hinzugekommen ist (Block Themes haben keinen Theme Customizer!) für das nur zu Verwirrung. Ich füge das wieder hinzu.

Ich sehe auch keinen zwingenden Grund, das Favicon mit der Sonnenblume zu erzwingen. Auch wenn jemand die Nutzungsbedingungen akzeptiert, sei es ihm freigestellt, ein modifiziertes Website Icon zu verwenden. In PR #598 wird das ermöglicht. Die Sonnenblume ist so lange gesetzt, wie kein "Custom" Website Icon konfiguriert ist.
