### ISSUE TITLE
Schrift nicht lesbar beim Hovern des Menütabs im Personal-Layout

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#605]
Beim Hover-Effekt des aktuell aktiven Menütabs im Personal-Layout ist die Schriftfarbe nicht sichtbar. Beim Hovern des nicht aufgerufenen Highlight-Buttons, ist der Text zu hell. Der Text wird dadurch unlesbar.

Schritte zur Reproduktion:
1. Bewege den Mauszeiger über einen aktiven Menütab.
2. Beobachte die Veränderung der Schriftfarbe beim Hover-Effekt.

Erwartetes Verhalten:
Die Schriftfarbe sollte beim Hover-Effekt klar und deutlich sichtbar bleiben, um die Lesbarkeit sicherzustellen.

Tatsächliches Verhalten:
Die Schriftfarbe ändert sich so, dass sie nicht mehr lesbar ist.

Screenshot:
![image](https://github.com/verdigado/sunflower/assets/122517567/f37411ca-8030-451b-b539-df4751c2247f)
![image](https://github.com/verdigado/sunflower/assets/122517567/0901a8f2-d600-48b1-9a02-2b1ed4f67cde)

**Comment by albig** [comment]
Danke. Wir kümmern uns.
