### ISSUE TITLE
Highlight-Buttons sehen vermutlich nicht so aus wie sie sollten

### ISSUE THREAD

**Issue by b90g** [verdigado/sunflower#606]
![grafik](https://github.com/verdigado/sunflower/assets/63392812/57242499-4b68-4e9e-a1f9-b56ac5f10e92)

hätte jetzt eher sowas erwartet:

![grafik](https://github.com/verdigado/sunflower/assets/63392812/d4e6de79-b8c0-4ba3-a931-abe2ad305a10)

**Comment by b90g** [comment]
https://wordpress02.gcms.verdigado.net/teeestkalender/

ich kriegs nicht reproduziert... ;/

**Comment by albig** [comment]
ggf. related zu #605
