### ISSUE TITLE
Weißen Bereich zwischen Hauptmenü im "Personal"-Layout und oberen Rand entfernen

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#612]
Beim "Personal"-Layout ist ein weißer Bereich zwischen grünen Hintergrund und oberen Rand. Beim scrollen verschwindet der, was den Übergang nicht flüssig macht.
![330068207-6565b57f-0c65-4ae5-961e-75407b4097d8](https://github.com/verdigado/sunflower/assets/122517567/22e176bf-c2d7-4301-b072-4d8fa04160f8)
Beim scrollen: ![330068207-6565b57f-0c65-4ae5-961e-75407b4097d8](https://github.com/verdigado/sunflower/assets/122517567/cf35e7a3-5ef5-4ce9-b9de-fde701d28854)

**Comment by HueHa-v** [comment]
Auch hier werden weitere Details benötigt. Dieser Effekt scheint nicht in jedem Fall aufzutreten.

**Comment by FloJuh** [comment]
Ich habe das Problem gefunden. Es liegt an folgendem Codeabschnitt:
`#navbar-sticky-detector.header-personal {
    height: 1px;
    background: #fff;
}`
