### ISSUE TITLE
Grüner Hintergrund beim Custom Logo im "Personal"-Layout anzeigen

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#614]
Beim "Personal"-Layout und Ablehnung der Nutzungsbedingungen wird der grüne Hintergrund beim Custom Logo nicht angezeigt.

Der grüne Hintergrund sollte beim Custom Logo beibehalten werden, da viele einfach nur etwas zur Sonnenblume hinzufügen.

**Comment by HueHa-v** [comment]
Wir haben uns bewusst dagegen entschieden. Die Menschen, die es benötigen sind frei dies über das Custom CSS einzubinden. Es gibt auch Menschen, die bei einem Custom Logo einen Verwendungszweck abseits der Grünen. Zudem ist das allgemeine Logo von der Partei so im CI vorgeschrieben.

**Comment by FloJuh** [comment]
Wie beim "Standard"-Layout (https://sunflower-theme.de/documentation/customcss/#hintergrundfarbe-fur-logo-im-sticky-menu-anpassen) wäre eine Erweiterung der Doku schön: 
```
.header-personal .img-container {
    background-color: #005437;
}
```
