### ISSUE TITLE
iCal Termin-Import: Error bei Terminen mit Startzeit = Endzeit

### ISSUE THREAD

**Issue by evaris1107** [verdigado/sunflower#617]
Hallo, beim iCal-Import wirft die Website folgenden Error:

_Ein Fehler vom Typ E_ERROR wurde in der Zeile 126 der Datei /mnt/web505/b3/43/510497743/htdocs/Gruene-Fuerth-Land/wp-content/themes/sunflower/functions/icalimport.php verursacht. Fehlermeldung: Uncaught Error: Call to a member function getDateTime() on null in /mnt/web505/b3/43/510497743/htdocs/Gruene-Fuerth-Land/wp-content/themes/sunflower/functions/icalimport.php:126
Stack trace:
#0 /mnt/web505/b3/43/510497743/htdocs/Gruene-Fuerth-Land/wp-content/themes/sunflower/functions/icalimport.php(240): sunflower_icalimport()
#1 /mnt/web505/b3/43/510497743/htdocs/Gruene-Fuerth-Land/wp-content/themes/sunflower/functions/options/class-sunflowereventsettingspage.php(64): sunflower_import_icals()
#2 /mnt/web505/b3/43/510497743/htdocs/Gruene-Fuerth-Land/wp-includes/class-wp-hook.php(324): SunflowerEventSettingsPage->create_sunflower_events_options_page()
#3 /mnt/web505/b3/43/510497743/htdocs/Gruene-Fuerth-Land/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /mnt/web505/b3/43/510497743/htdocs/Gruene-Fuerth-Land/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /mnt/web505/b3/43/510497743/htdocs/Gruene-Fuerth-Land/wp-admin/admin.php(259): do_action()
#6 {main}
  thrown_

Es geht also scheinbar um die Endzeit eines Termins, es handelt sich dabei um diesen (Google Kalender): 
![Screenshot (13)](https://github.com/verdigado/sunflower/assets/72270664/68377c9a-14cc-46a0-9e67-4fc546f0aeb9)

Ändere ich das Ende dieses Termins auf eine Uhrzeit ungleich 19:00 Uhr (Startzeit), taucht der Fehler nicht mehr auf. Komischerweise haben einige andere importierte Termine ebenfalls Startzeit = Endzeit (siehe gruene-fuerth-land/termine), ohne einen Error zu verursachen. Liegt es vielleicht daran, dass es sich um den zeitlich nahegelegendsten und damit ersten zu importierenden Termin handelt??

Versionen: WordPress-Version 6.5.3, sunflower (Version 2.1.3), PHP-Version 8.2.18
Custom Termin-Einstellungen: Zeitzonen-Fix: enabled, Zeitspanne: 6 weeks

**Comment by albig** [comment]
Danke für den detailierten Report.

Vermutlich ist das identisch mit #609 und bereits in #610 behoben. Wird Teil von Version 2.1.4, die Anfang der kommenden Woche veröffentlicht wird.
