### ISSUE TITLE
Abstand zwischen textbalken entfernen

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#618]
Zwischen den Textbalken ist eine Lücke, die es nach dem Grundlagendesign (S. 16-17) nicht geben sollte.

![SharedScreenshot1](https://github.com/verdigado/sunflower/assets/122517567/0818f0c6-b9ec-4b21-abe2-060b27538cdb)

**Comment by HueHa-v** [comment]
Wir brauchen zur Analyse weitere Details. Die Lücke scheint nicht in jedem Kontext aufzutreten. Schick dich gerne eine Beispielseite, wo wir das nachschauen können.

**Comment by FloJuh** [comment]
Die Lücke geht mit `textbalken links-eins` bzw. `textbalken links-zwei` weg. Anders als in der Doku darf kein Punkt vor `textbalken` oder `links-eins` bzw. `links-zwei` stehen.

Bei der Sunflower-Seite "Kandidierende" funktioniert es übrigens nicht ordnungsgemäß:
![image](https://github.com/verdigado/sunflower/assets/122517567/0a06d7bc-0977-4844-96ae-a3d2d3f0ce98)
