### ISSUE TITLE
Links von Galeriebildern öffnen nicht

### ISSUE THREAD

**Issue by FriSchl** [verdigado/sunflower#625]
Wir möchten von Bildern in einer Galerieansicht mit Links auf Seiten oder Artikel springen.
Das lässt sich zwar eingeben, aber beim Anklicken auf der Webseite poppt nur ein Kreis auf, der sich vor sich dreht, aber zu nichts führt.
Wäre schön eine Abhilfe zu bekommen.
Danke fritz

**Comment by albig** [comment]
Gibt es ein Beispiel, das man sich anschauen kann?
