### ISSUE TITLE
Kontaktformular: Bestätigungsmail an Absender schicken

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#626]
Aktuell erhält der Absender nur eine Bestätigungsnachricht, wie im Screenshot dargestellt:
![image](https://github.com/verdigado/sunflower/assets/122517567/ac89244b-0e35-4672-8934-d17ce397b528)

Neben der Bestätigungsnachricht soll das Formular auch an die im Formular angegebene E-Mail-Adresse gesendet werden. Dies verbessert die Benutzererfahrung, da der Empfänger eine Kopie des Formulars in seinem Posteingang hat.

**Comment by albig** [comment]
Ich kann mir vorstellen, das als optionales Feature hinzuzufügen. Default wäre "aus".

Es kann problematisch sein, weil das Formular an die eingegebene E-Mail-Adresse Mails schickt. Das kann für den Versand von Spam missbraucht werden.
