### ISSUE TITLE
Kontaktformular: Mehrfach Eingabe unterbinden

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#628]
**Problem:**
Mehrfaches Klicken auf die Schaltfläche "Abschicken" im Kontaktformular führt dazu, dass das Kontaktformular mehrfach abgeschickt wird, bevor die Seite neugeladen hat und die Bestätigungsnachricht angezeigt wird.

**Beschreibung:**
Wenn ein:e Nutzer:in die Schaltfläche "Abschicken" im Kontaktformular schnell hintereinander mehrfach anklickt, wird das Formular jedes Mal gesendet. Dies geschieht solange, bis die Bestätigungsnachricht angezeigt wird. Dies kann zu doppelten oder sogar mehrfachen Einsendungen des Kontaktformulars führen.

Je länger das neu Laden benötigt, desto mehr ist man gewillt, nochmal auf den Knopf zu drücken.

**Erwartetes Verhalten:**
Beim ersten Klick auf die Schaltfläche "Abschicken" sollte die Schaltfläche deaktiviert werden, um weitere Klicks zu verhindern. Alternativ könnte ein Ladeindikator angezeigt werden, bis die Bestätigungsnachricht erscheint, um sicherzustellen, dass das Formular nur einmal abgeschickt wird.

**Schritte zur Reproduktion:**
1. Öffne das Kontaktformular.
2. Fülle die erforderlichen Felder aus.
3. Klicke schnell hintereinander mehrfach auf die Schaltfläche "Abschicken".

**Comment by albig** [comment]
Ich konnte das nur künstlich reproduzieren, indem ich die Skript-Verarbeitung verlangsamt habe. Das kann natürlich im Server-Betrieb passieren. Tatsächlich ist mir bisher nicht gemeldet worden, dass es Probleme mit mehrfach abgesendeten Formularen gab.

Trotzdem deaktiviere ich den Button nach dem Submit in PR #629. Sollte ja nicht schaden.
