### ISSUE TITLE
Template für Linkseite integrieren

### ISSUE THREAD

**Issue by georgloesel** [verdigado/sunflower#638]
Ein Template für eine Seite, in der verschiedene Links gesammelt werden könnten wäre sinnvoll. 
ähnlich linktree oder https://www.wonderlink.de/

Idee: https://chatbegruenung.de/channel/sunflower-wordpress?msg=53zDgFDwlxAnEUqTt

das ganze als Bestandteil von Sunflower um externe Dienste zu vermeiden.

**Comment by albig** [comment]
Das ist also nur eine Seite mit

* Bild (Gravatar) -> möglich mit WP Image Block
* Hintergrund-Bild --> auch möglich, denk ich
* Social-Media-Buttons -> möglich mit WP Sunflower "Metadata"-Block
* Button mit Text und Link -->möglich mit WP Button Block

Daraus könnte man ein Vorlagen-Template basteln, was ähnlich dem 2-Personen, 3-Personen Template wäre.
