### ISSUE TITLE
"Metadaten / Social-Media Profile" Block öffnet E-Mail nicht mehr im Mail-Programm

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#643]
Der Block "Metadaten / Social-Media Profile" hat bisher die angegebene E-Mail-Adresse im Standard-Mail-Programm geöffnet. Diese Funktion scheint nun nicht mehr zu funktionieren.

**Schritte zur Reproduktion:**
1. Gehe zu dem Block "Metadaten / Social-Media Profile".
2. Klicke auf das E-Mail/Brief-Symbol.
3. Beobachte das Verhalten des Browsers.

**Erwartetes Verhalten:**
Das Standard-Mail-Programm sollte sich öffnen und eine neue E-Mail mit der angegebenen Adresse als Empfänger*in erstellen.

**Tatsächliches Verhalten:**
Beim Klicken auf das E-Mail-Symbol wird ein neuer Tap geöffnet.

**Umgebung:**
Betriebssystem: Windows 10
Browser: Chrome
Theme-Version: 2.1.5

**Zusätzliche Informationen:**
Funktionierte vorher mit der Version: 2.0

**Comment by albig** [comment]
Was steht denn im Feld "URL"? Da müsste das Protokoll mit aufgeführt werden. Also z.B. `mailto:testmail@example.com`.

Ist die Option `SUNFLOWER_EMAIL_SCRAMBLE_NO` eventuell auf `true` gesetzt?

**Comment by FloJuh** [comment]
Früher war es ausreichend, einfach die Mailadresse anzugeben, ohne `mailto:` zu verwenden.

Nein, wir haben die E-Mail-Verschleierung nicht verändert.

**Comment by albig** [comment]
Danke für das Feedback. Muss ich mir mal 2.0 noch mal anschauen um das nachzuvollziehen.

**Comment by albig** [comment]
Ich hab jetzt ein 2.0.9 am Laufen. Das verhält sich genauso. Ohne `mailto:` wird das nicht erkannt.

**Comment by FloJuh** [comment]
Vielen Dank für deine Mühe! Ich habe es ebenfalls getestet und bin zum gleichen Ergebnis gekommen. Anscheinend habe ich irgendwann aufgehört, das `mailto:` zu setzen – mein Fehler. Ich ändere dann mal 10 Websites 🙄
