### ISSUE TITLE
Fehlende Übersetzung vom Kontaktformular

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#648]
Im Kontaktformular fehlt die deutsche Übersetzung. Siehe Screenshot:
![image](https://github.com/verdigado/sunflower/assets/122517567/43295416-052d-4ad2-9f55-e6db491d0573)

**Comment by albig** [comment]
Danke. Die Labels sind schon da, aber da fehlt wohl die Aktualisierung mit `make-json'. Hohl ich bald nach.
