### ISSUE TITLE
Hintergrundfarbe bei Blöcken nicht mehr in voller Breite

### ISSUE THREAD

**Issue by gruenenf** [verdigado/sunflower#675]
## Fehler
Moin,
leider ist nach einem Wordpress Update (Sunflower wurde die letzten Monate ja nicht aktualisiert, oder?)
die Hintergrundeinfärbung nicht mehr durchgängig. 

###
![Bildschirmfoto 2024-07-25 um 12 05 53](https://github.com/user-attachments/assets/6fd89ea7-ab8b-4a1b-baf9-9b3ac47a04f3)

Vielen Dank und LG aus dem Norden!

**Comment by gruenenf** [comment]
Das zerschießt leider das ganze Design. 

`
<div class="wp-block-group has-sand-background-color has-background"></div>

`
<img width="1435" alt="Bildschirmfoto 2024-07-30 um 15 32 03" src="https://github.com/user-attachments/assets/75a5e747-679e-431b-91d4-58c9858609fc">

**Comment by albig** [comment]
> Enthält er den "Neueste Beiträge (Sunflower)"-Block, gibt es aber Probleme, die ich mit dem nächsten Release fixe.

Wie oben beschrieben. Das ist sicher der Neueste Beiträge Block.

**Comment by gruenenf** [comment]
> > Enthält er den "Neueste Beiträge (Sunflower)"-Block, gibt es aber Probleme, die ich mit dem nächsten Release fixe.
> 
> Wie oben beschrieben. Das ist sicher der Neueste Beiträge Block.

Ah Überlegen - Danke!
