### ISSUE TITLE
"Block hinzufügen Button" fehlt im Editor

### ISSUE THREAD

**Issue by gruenenf** [verdigado/sunflower#690]
## Describe the bug
Das Hinzufügen von neuen Abschnitten / Blöcken ist leider nicht mehr möglich. Wenn man mit der Maus an die Seite fährt, taucht der "Hinzufüge Button" auf, sobald man drüber gehen will, verschwindet der. 
 
### Website or Screenshots

https://github.com/user-attachments/assets/1e1f47bd-1516-4e69-891a-f42052ffa5e5

### Environment
- Mac Book Air M1
- Brave, Safari

**Comment by albig** [comment]
Da kann Sunflower als Theme nichts machen. Das ist das allgemeine WordPress-Verhalten.

Hilfreich ist hier die Listenansicht anzuschalten und dort dann z.B. "Danach hinzufügen" wählen.

![2024-08-06_11-21](https://github.com/user-attachments/assets/88a10ba7-e0fa-4dd9-a040-9ba86f89c013)

**Comment by gruenenf** [comment]
> Da kann Sunflower als Theme nichts machen. Das ist das allgemeine WordPress-Verhalten.
> 
> Hilfreich ist hier die Listenansicht anzuschalten und dort dann z.B. "Danach hinzufügen" wählen.
> 
> ![2024-08-06_11-21](https://private-user-images.githubusercontent.com/3354500/355391831-88a10ba7-e0fa-4dd9-a040-9ba86f89c013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjI5MDcsIm5iZiI6MTcyMzAyMjYwNywicGF0aCI6Ii8zMzU0NTAwLzM1NTM5MTgzMS04OGExMGJhNy1lMGZhLTRkZDktYTA0MC05YmE4NmY4OWMwMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMDkyMzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjgxYTM1YmE3ZDA2ODIyOTZhZmE1NzZjMzg1NjUwOGE1NmNlMTg4ZjdmMDNhNzlhODZmNmZkMjU0NmVjNzQ1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TosJV81VG9Wu8IBsDORNeszkGdwOzqAFyzK-6mg1QZM)

Ah, die Funktion kannte ich noch nicht – vielen Dank!
