### ISSUE TITLE
header-personal: Grüner Hintergrund beim Logo nicht füllend in der mobilen Ansicht

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#693]
## Describe the bug
Im header-personal ("Personal"-Layout) wird in der mobilen Ansicht der grüne Hintergrund hinter dem Logo nicht ausfüllend angezeigt.

**Schritte zur Reproduktion:**
1. Öffne eine Webseite im "Personal"-Layout auf einem mobilen Gerät oder zoome auf ≥ 500 %
2. Beobachte den grünen Hintergrund beim Logo

### Website or Screenshots
![SharedScreenshot](https://github.com/user-attachments/assets/3c198522-c278-4e60-a85d-289fbda555d2)

### Environment
 - Devise: Smartphone
 - OS: Android
 - Browser chrome
 - Version of the sunflower theme: 2.1.8
 - WordPress version: 6.6.1
 - PHP version: 8.2.21

## Additional context
Betrifft auch das Costum Logo: https://github.com/verdigado/sunflower/pull/635

## Possible Fix
`.header-personal .img-container` bzw. `.header-personal .img-container.sunflower-logo` vergrößern, sodass sie den gesamten Bereich bis zu den beiden Rändern ausfüllen.

**Comment by albig** [comment]
Die Darstellung wird ab Bootstrap Breakpoint `sm` (<576px) unschön. Ich denke, das ist das Thema dieses Issues.

Eingeführt haben wir das hier: https://github.com/verdigado/sunflower/commit/fae5e2ccb330858d47f0edb1d6377c97c28957af und die konkrete Zeile im Sass ist diese hier: https://github.com/verdigado/sunflower/blob/c1d61b81ecc1593852865cc14969018a6cd87059/sass/_header.scss#L272

**Comment by FloJuh** [comment]
Ähnliches Problem beim "Standard"-Layout: https://gruene-fraktion-ts.de/?
