### ISSUE TITLE
Aufrufen von Menüpunkten mit drop-down-Menü braucht 2 Klicks

### ISSUE THREAD

**Issue by stiglers-eponym** [verdigado/sunflower#702]
Erklärung anhand des Beispiels https://sunflower-theme.de/demo mit Hauptmenüpunkt "Partei":

Fährt man am Desktop mit der Maus über den Menüpunkt "Partei", so wird darunter das drop-down-Menü angezeigt. Klickt man dann auf "Partei", so bleibt das Menü ausgeklappt. Für den User ergibt sich der Eindruck, dass der Punkt "Partei" kein eigener Link ist (schließlich hat der Klick darauf zunächst scheinbar nichts bewirkt). Klickt man ein zweites mal auf "Partei", so folgt man dem Link (/partei).

## Problem
Seiten (im Beispiel /partei) werden nicht gefunden, da sie erst beim zweiten Klick auf den Menüpunkt aufgerufen werden.

## Vorschlag
- Entweder das user interface ändern, sodass bereits ein Klick ausreicht wenn das drop-down Menü sichtbar ist;
  - in assets/js/frontend.js, Zeile 203 wird auf die Klasse "show" geprüft, aber bei mouse hover ist das drop-down Menü sichtbar, ohne dass die Klasse "show" gesetzt ist.
- oder darauf hinweisen, dass wichtige Seiten nicht auf diese Art versteckt werden sollten.

**Comment by albig** [comment]
Danke für Dein Issue und die Analyse. Das Verhalten ist mir auch aufgefallen. Hintergrund ist, dass das Boostrap-Framework keine Oberpunkte in Dropdown-Menüs vorsieht und bewusst nicht klickbar macht. Das find ich persönlich auch seltsam und das Sunflower hatte schon immer eine JavaScript-Bastelei enthalten, die das trotzdem ermöglicht.

Ich schau noch mal, ob ich es besser hinbekomme. Zu Berücksichtigen ist auch immer die Bedienung des Menüs per TAB-Taste (Barrierearmut).
