### ISSUE TITLE
Pixabay Stockfotos in Sunflower

### ISSUE THREAD

**Issue by gruenenf** [verdigado/sunflower#704]
## Describe the bug
Wir bekamen heute die Nachricht von unserem LV, dass Pixabay seit geraumer Zeit die Nutzung ihrer Bilder für politische Inhalte verboten hat. Wenn ich es richtig sehe, sind die Musterfotos in Sunflower Pixabay Fotos. Sollten diese nicht besser entfernt werden?

### Website or Screenshots
<img width="1187" alt="Bildschirmfoto 2024-08-20 um 15 49 52" src="https://github.com/user-attachments/assets/393ec689-3d0b-455e-a33f-045156b428ff">

## Possible Fix
Musterfotos löschen

**Comment by albig** [comment]
Ich kann das aus den [Nutzungsbedingungen von Pixabay](https://pixabay.com/de/service/terms/) nicht entnehmen. Auch wenn es da einen "schrägen" Passus gibt "_Du darfst keine Inhalte verwenden [...] die [...] in einem politischen Kontext stehen_". Frage mich, ob Sonnenblumen in einem politischen Kontext stehen...? 

Wenn Du da genauere Infos hast, dann gerne her damit. Ggf. auch lieber per [Chatbegrünung -> Sunflower Theme](https://chatbegruenung.de/channel/sunflower-wordpress).

Den Import von Stockfotos an sich halte ich für das Sunflower Theme für verzichtbar. Wir müssten aber die Templates und den neueste Termine-Block anpassen.

**Comment by gruenenf** [comment]
Ich habe dir die Nachricht einmal persönlich geschickt. Demnach kommt es wohl aktuell zu ersten Abmahnungen. 
LG

**Comment by ErwinBehner** [comment]
https://sunflower-theme.de/ und die Demoseite nicht vergessen. ;-)

**Comment by albig** [comment]
Danke für die Erinnerung!
