### ISSUE TITLE
Unterschiedlichkeit des Block-Elements Neuigkeiten und der Seite Aktuelles / Neuigkeiten

### ISSUE THREAD

**Issue by morange** [verdigado/sunflower#723]
## Describe the bug
Für die Seite "Aktuelles" des KV's werden Beiträge in chronologischer Reihenfolge und in zwei Spalten ausgegeben. 
Auf der Startseite, auf der wir das Block-Element für Neuigkeiten eingebunden haben, ist es möglich eine Spaltigkeit des Elementes frei zu bestimmen.

Für uns irritierend ist, dass die Beiträge der Seite "Aktuelles" hier in Spalten ausgegeben werden und nicht wie im Neuigkeiten Element.

### Website or Screenshots
Wir als KV Pinneberg wünschen uns, dass die Beiträge der Neuigkeiten Seite analog zum Block-Element "Neuigkeiten" passt. Die Ausgabe der Beiträge soll chronologisch absteigend anhand des Veröffentlichungsdatums erfolgen. Hierbei ist es völlig normal, dass Beiträge redaktionell vorbereitet und zu einem späteren Zeitpunkt veröffentlicht werden. Wir nutzen außerdem intensiv die automatische Import-Funktion aus der Grünen Wolke.

Wir würden uns freuen, wenn ihr die Ausgabe der beiden Typen angleicht, so dass die Ausgaben besser zueinander passen.

**Comment by FloJuh** [comment]
Beispiel:
Die Beiträge https://gruene-pi.de/2024/04/11/attraktivitaet-der-bahn-steigern-bahnachse-hamburg-elmshorn-nicht-aus-den-augen-verlieren/, https://gruene-pi.de/2024/03/28/frieden-freiheit-fahrradwege/ müssten nach dem Veröffentlichungsdatum auf https://gruene-pi.de/aktuelles/ angezeigt werden, stehen aber auf https://gruene-pi.de/aktuelles/page/2/

**Comment by albig** [comment]
Ich verstehe bisher folgende Punkte:

1. Der Block "Neueste Beiträge (Sunflower)" kann 1/2/3-spaltige Ausgabe. Die "Archiv"-Ansicht ist aber fix zweispaltig.
Beispiel(e): 
  * https://gruene-pi.de/?post_type=post 
  * https://gruene-pi.de/category/kreis-pinneberg/
  * https://gruene-pi.de/aktuelles/
2. Es gibt Artikel, die in der "Archiv"-Ansicht nicht nachvollziehbar einsortiert werden.
Beispiel: https://gruene-pi.de/2024/04/11/attraktivitaet-der-bahn-steigern-bahnachse-hamburg-elmshorn-nicht-aus-den-augen-verlieren/

Punkt 1 ist tatsächlich so und nicht einfach umsetzbar, weil die Archiv-Seite eben kein Block ist, den man konfigurieren kann.

Punkt 2 kann ich nicht erklären. Ist an den genannten Beiträgen irgendetwas "besonders"? Üblicherwiese ist die Reihenfolge chronologisch nach Veröffentlichung. Das stimmt hier aber nicht.

**Comment by FloJuh** [comment]
Zu Punkt 2: Die Beiträge weisen keine Besonderheiten auf. Ich habe gerade den Beitrag https://gruene-pi.de/2024/03/28/frieden-freiheit-fahrradwege/ bearbeitet, und dieser ist von Seite 2 auf Seite 1 an die erste Position gerutscht. Daraus schließe ich, dass die Beiträge nicht nach dem Veröffentlichungsdatum, sondern antichronologisch nach dem Last-Modified-Datum sortiert werden

**Comment by morange** [comment]
Wir hatten dieses [Plugin](https://de.wordpress.org/plugins/wp-last-modified-info/) in unserer Installation aktiv. Dann werden wir uns da mal was anderes suchen. ;) Danke für deine Hilfe.

**Comment by albig** [comment]
Seltsames Plugin: `Allows you to sort posts/pages in last updated/modified date-time order.`. Ja schön, aber es erlaubt nicht nur sondern erzwingt die Sortierung nach last-modified. Es gibt gar keine Option, das abzuwählen. 

Danke, das erklärts. Kann das lokal mit dem Plugin auch nachvollziehen.

**Comment by morange** [comment]
Besten Dank

**Comment by FloJuh** [comment]
Eigentlich sollte das Plugin nur das Last-Modified-Datum anzeigen. Lustig, dass es erst jetzt aufgefallen ist. Wir nutzen es schon seit 2020.
