### ISSUE TITLE
index.php: Kein sidebar widget im footer für /?post_type=post

### ISSUE THREAD

**Issue by stiglers-eponym** [verdigado/sunflower#725]
## Template `index.php` zeigt kein sidebar widget im footer
Die "sidebar" gehört optisch auf fast allen Seiten zum Footer und wird direkt über diesem angezeigt. Eine Ausnahme bildet die Blog-Seite, z.B. <https://sunflower-theme.de/demo/?post_type=post>.

Ist das beabsichtigt?

### Ursache im Code
In `sunflower/index.php` steht `get_footer();` allein am Ende, während andere Templates (`page.php`, `archive.php`, ...) dort `get_sidebar(); get_footer();` stehen haben.

**Comment by albig** [comment]
Denke, das ist keine Absicht nur bisher ist es niemandem aufgefallen. Danke dafür!
