### ISSUE TITLE
[Bug] Fehlverhalten (optisch) des Menüs in der mobilen Ansicht

### ISSUE THREAD

**Issue by HueHa-v** [verdigado/sunflower#727]
## Beschreibe den Fehler
In der mobilen Ansicht von Sunflower hat das Menü ein ungewöhnliches Verhalten:
Klickt man auf ein Oberes Menü-Element und klappt dieses auf, wird es nach Links gerückt (anstatt in der Mitte zu bleiben). Alle Kinder-Elemente darunter sind ebenfalls Links ausgerichtet.

### Website oder Screenshots
![2024-09-10_09-20](https://github.com/user-attachments/assets/ffb1f679-b4fd-437a-ba04-82e6a8275996)

**Comment by albig** [comment]
Das ist tricky und liegt am Verhalten von `flex`. Der ganze, oben rot markierte Bereich ist breiter als der Hauptbmenü-Punkt "Partei" und dann ist noch alles linksbündig. Ganz verrückt wird es, wenn der Haupt-Menüpunkt einen Highlight-Button enthält.
Das muss man mal in Ruhe auseinander nehmen.

**Comment by FloJuh** [comment]
Sieht jetzt besser aus, danke!

Allerdings öffnet sich das Menü nicht so flüssig. Es öffnet sich zunächst, aber wenn es vollständig sichtbar ist, springt es leicht nach links, und die Trennlinien erscheinen erst danach.
