### ISSUE TITLE
Quelle der im Theme integrierten Bilder - Bilder ändern

### ISSUE THREAD

**Issue by FrankHeiLab** [verdigado/sunflower#729]
## Describe the bug
Nicht wirklich ein Bug, aber drängendes Problem: Pixabay hat seine Nutzungsbedingungen geändert, die Bilder dürfen nicht mehr für politische Zwecke eingesetzt werden.
Ich wollte als Anfrage ans Sunflowertheme richten, welche Quelle Ihr für die integrierten Bilder, z.B. beim Block: Termine habt.

Daran knüpft sich die Frage an, gibt es eine Möglichkeit, diese Bilder zu ändern? (Habe in der Dokumentation nichts gefunden.

Bin nicht versiert in Github, aber hier gelandet, beim Versuch, das Sunflower Team zu kontaktieren.

Danke für eine Antwort
Frank aus dem Bodenseekreis

### Website or Screenshots
If applicable, add an link to the website or add screenshots to help explain your problem.

### Environment
- Desktop/ Smartphone
 - Devise: Desktop/ Smartphone
 - OS: [e.g. iOS/ Android]
 - Version of the sunflower theme [e.g. 2.1.5 for recent]
 - WordPress version [e.g. 6.5]
 - PHP version [e.g. 8.2]

**Comment by FloJuh** [comment]
Duplicate of #704

**Comment by albig** [comment]
Das Sunflower-Theme bringt nur ein Bild für den Block "Nächste Termine" mit. In Version 2.2 ist das von Pixabay auf Unsplash geändert worden.

Abgeschaltet wurde auch die Möglichkeit, sich ein paar Bilder vom Sunflower-Server in die eigene Mediathek zu importieren. Das war nett gedacht, aber die Prüfung ob Bilder verwendet werden können muss jeder Webseitenbetreiber selbst machen. Die bereitgestellten Pixabay.Fotos haben wir entfernt. Die können auch ältere Sunflower-Themes nicht mehr importieren. Ich denke, dieses Feature wude auch eher selten genutzt.

Wenn Ihr z.B. den Block "Meine Themen" eingefügt habt und nie die Bilder angepasst habt, dann habt ihr da Links zu Bildern auf sunflower-theme.de drin. Die Bilder haben wir dort zwar ersetzt, aber es ist grundsätzlich nicht zu empfehlen Bilder von externen Servern einzubinden. Nehmt dafür bitte lokale Bilder aus Eurer Mediathek.
