### ISSUE TITLE
Submenü auf Smartphone schliesst sich von alleine 

### ISSUE THREAD

**Issue by MiObe** [verdigado/sunflower#733]
Problem bei Smartphone-Bedienung: Das Hamburger Menü öffnet sich bei der Auswahl eines Menüpunkts, wählt man dann einen Menüpunkt mit einem Submenü aus wird es aber von alleine geschlossen. Man hat keine Chance eine Auswahl aus diesem Submenü zu treffen. Getestet auf Android (Version 11 und 14).
Nachvollziehbar auf der Seite https://gruene-freising.de  Beispielsweise Menüpunkt "Kreisverband" oder "Der Kreistag"

**Comment by albig** [comment]
Danke. Kann ich reproduzieren. Ist vermutlich eine Nebeneffekt von https://github.com/verdigado/sunflower/pull/703
