### ISSUE TITLE
syntax error, unexpected token

### ISSUE THREAD

**Issue by Drakemaster** [verdigado/sunflower#734]
## Describe the bug
Wordpress hat mir heute per Mail einen Fehler gemeldet. Die Webseite scheint aber auf den ersten Blick wie erwartet zu funktionieren.

Fehler-Details
==============
Ein Fehler vom Typ E_PARSE wurde in der Zeile 24 der Datei /var/www/vhosts/hosting160270.ae81c.netcup.net/httpdocs/wp-content/themes/sunflower/functions/options/class-sunflowerfirststepspage.php verursacht. Fehlermeldung: syntax error, unexpected token ")"

### Website or Screenshots
https://gruene-wds.de/

### Environment
WordPress-Version 6.6.2
sunflower Version 2.2.0
PHP-Version 8.0.30

**Comment by albig** [comment]
Seit Sunflower 2.1.0 wird mindestens PHP 8.2 vorausgesetzt.

In Eurem Fall nutzt ihr offenbar PHP 8.0 und das verwendete Sprachkonstrukt wird nicht verstanden. Das gibt es erst ab PHP 8.1. Hintergrund: https://php.watch/versions/8.1/first-class-callable-syntax

Es wäre also an der Zeit bei Euch PHP zu aktualisieren. PHP 8.0 wird seit 9 Monaten nicht mehr supported: 
https://www.php.net/supported-versions.php
