### ISSUE TITLE
Kalender-Import scheitert, wenn die Event-Beschreibung (bestimmte) Emojis enthält

### ISSUE THREAD

**Issue by amigu** [verdigado/sunflower#736]
Bei uns (grüne-harburg.de) scheiterte der Kalender-Import, wenn eine Event-Beschreibung das grüne Herz-Emoji enthielt: 💚

Das `wp_insert_post( (array) $post, true )` in Zeile 115 in `icalimport.php` gibt dann einen Fehler zurück. 

Etwas unglücklich ist, dass durch diesen Fehler bei einem einzelnen Event der gesamte Import scheitert und dadurch *gar keine* Termine mehr auf unserer Seite angezeigt wurden. Auch eine etwas detailliertere Fehleranzeige als "Could not copy post" beim manuellen Kalenderimport wäre hilfreich, z.B. durch Anzeige des event summaries, so dass deutlich wird, welches Kalenderevent das Problem verursacht. 

Vielen Dank für eure Arbeit und Grüße aus Harburg 👋

**Comment by albig** [comment]
Das kann ich leider noch nicht nachvollziehen. Mein Testtermin in der Wolke mit dem grünen Emoji wird klaglos importiert.

Könnt Ihr Beiträge mit Emojis im Text anlegen oder Termine manuell anlegen? Was ist die volle Fehlermeldung (ggf. aus Apache oder nginx error-Log) oder kommt ihr da nicht dran?

Ansonsten wäre ein Link zur ICS-Datei hilfreich.

**Comment by albig** [comment]
Könnt Ihr mir einen ICS-Link zukommen lassen, @amigu um den Fehler untersuchen zu können. Gerne auch per Chatbegrünung: https://chatbegruenung.de/direct/biggaale

**Comment by amigu** [comment]
Hi Alexander, ich habe gerade keinen Zugang zu dem Rechner auf dem ich das
kaputte ics file noch haben müsste, ich kann nächste Woche nachschauen. Mit
dem aktuellen ics Link klappt es ja wider. Vielen Dank fürs nachhaken, ich
melde mich wenn ich das ics zum reproduzieren habe.

Michael Frischeisen-Köhler
Auf der Jahnhöhe 14 | 21075 Hamburg
Tel.: 040-858717 | Mobil: 0163-3540548


Alexander Bigga ***@***.***> schrieb am Mo. 28. Okt. 2024 um
16:20:

**Comment by albig** [comment]
Nicht reproduzierbar. Vermutlich stimmte im o.g. Fall der Datenbank-Zeichensatz nicht (`utf8` statt `utf8mb4`?). Damit konnten generell keine Emojis abgespeichert werden.
