### ISSUE TITLE
Größe der Beitragsbilder in der Übersicht nicht optimiert

### ISSUE THREAD

**Issue by amigu** [verdigado/sunflower#753]
In der Post-Übersicht scheint immer die Originalgröße des Beitragsbilds angezeigt zu werden, was bei großen Bildern die Performance der Seite erheblich verlangsamt. In der Einzelansicht wird dagegen eine skalierte Größe gewählt, die für die Fenstergröße sinnvoll ist. 

Offenbar erzeugt der selbe [Aufruf von the_post_thumbnail()](https://github.com/verdigado/sunflower/blob/59f5970c21e9c118e4c345195ba660b285e4909f/inc/template-tags.php#L177) in der Einzelansicht ein vernünftiges `srcset`, in der Übersicht aber nicht. 

Wir könnten die Bilder natürlich von Hand verkleinern, so dass auch die Originalgröße nicht unerträglich groß ist, aber eigentlich bringt Wordpress ja die Funktionalität mit, um nur sinnvolle Bildgrößen zu laden, dachte ich. 

Für ein Beispiel mit momentan schmerzhaft großen Bildern auf der Startseite siehe https://gruene-harburg.de/ :)

**Comment by albig** [comment]
Ich kann leider nicht erkennen, warum WordPress das `srcset` in dem einen Fall entfernt. Intern wird es angelegt. 

Das Problem taucht offenbar auf, wenn der Block "Neueste Beiträge (Sunflower)" auf einer Seite eingebunden wird. Dann trifft wohl `is_singular()` in https://github.com/verdigado/sunflower/blob/main/inc/template-tags.php#L166 zu und das Bild wird in voller Auflösung ausgegeben. Das macht aber nur Sinn im Falle eines Einzel-Posts.

Das schau ich mir mal an. Insofern ist das durchaus ein Bug.

In Eurem Fall würde ich unbedingt empfehlen für Fotos keine PNG-Dateien zu verwenden. Das ist einfach um den Faktor ~5 größer als ein JPG. PNG ist dafür einfach nicht geschaffen. Nutzt PNG gerne für Grafiken, Logos aber eben nicht für Fotos. Ihr müllt Euch ja nur die Instanz voll, weil davon ja auch die ganzen kleineren Bilder abgeleitet und abgespeichert werden - im selben, ungeeigneten Format.
