### ISSUE TITLE
Terminübersicht: Nur aktuelle Schlagwörter anzeigen

### ISSUE THREAD

**Issue by jemand-anderes** [verdigado/sunflower#754]
Wäre es möglich, bei der Terminübersichtsseite nur die Kategorien/Schlagwörter anzuzeigen, die in den aufgelisteten nächsten Terminen getaggt sind? Aktuell werden sämtliche Schlagwörter angezeigt, auch für Termine in der Vergangenheit, die in der Terminübersicht gar nicht mehr auftauchen. Das macht das Ganze nicht nur unübersichtlich, sondern auch frustrierend für die User, wenn bei den meisten Schlagwörtern nichts angezeigt wird.

**Comment by albig** [comment]
Müsste man sich genauer anschauen. Hast du ein Beispiel? URL oder Screenshot würde weiter helfen.

**Comment by albig** [comment]
Danke. Das hilft sehr.
