### ISSUE TITLE
header-personal: Ausklapp-Pfeil berührt button-highlight

### ISSUE THREAD

**Issue by FloJuh** [verdigado/sunflower#771]
## Describe the bug
Im `header-personal` berührt der Ausklapp-Pfeil den `button-highlight`.

### Screenshots
2.2.3:
![2 2 3](https://github.com/user-attachments/assets/0b42c088-87f9-4893-b06e-31356d40e54d)

2.2.0:
![2 2 0](https://github.com/user-attachments/assets/84626c5e-22ae-4491-921b-22ae5d7be97a)

`standard header` (2.2.3):
![2 2 3 standard](https://github.com/user-attachments/assets/156762b9-332f-4ddd-af6a-eefde87af2f5)

### Environment
 - Devise: Desktop
 - Browser: Firefox
 - Version of the sunflower theme: seit 2.2.2
 - WordPress version: 6.7
 - PHP version: 8.2.25

## Additional context
Der Platz für Menüpunkte im `header-personal` wurde seit Version 2.2.0 angepasst. In den Versionen 2.2.2 und 2.2.3 (kein Unterschied erkennbar) wurde dieser Platz für mehr Menüpunkte optimiert, was beibehalten werden sollte.

2.2.3:
![2 2 3 ganz](https://github.com/user-attachments/assets/32ec6f97-8b9c-41c0-b117-cbb585d2e997)

2.2.2 (der Vollständigkeit halber):
![2 2 2 ganz](https://github.com/user-attachments/assets/5ab76c08-dffd-4506-ad2d-9b9b95b35ce1)

2.2.1:
![2 2 1 ganz](https://github.com/user-attachments/assets/777f7f8b-db5e-49ad-bce2-c8c61a67721f)

2.2.0:
![2 2 0 ganz](https://github.com/user-attachments/assets/da979d95-38df-44dc-976f-399dfbbc579f)

**Comment by albig** [comment]
Danke für die Serie. Der Abstand des Dropdown-Pfeils zum Highlight ist natürlich zu verbessern. Hintergrund der ganzen Änderungen ist, das Menü sowohl mobil als auch im Desktop zu verbessern. Insbesondere bei den Dropdown-Menüs gab es mit 2.2.0 und 2.2.1 Probleme.
