### ISSUE TITLE
FEATURE CSP – Content-Security-Policy

### ISSUE THREAD

**Issue by morange** [verdigado/sunflower#793]
Gibt es von euer Seite die Möglichkeit CSP Regeln für die Härtung der WordPress Webseite einzubinden? … und uns als Betreiber der Webseiten eine gute Handreichung mitzugeben?

Erstellt habe ich diese Rules mit dem [Plugin HttpHeaders](https://de.wordpress.org/plugins/http-headers/). Das macht es schon ganz gut, hat aber die Eigenart die ausgewählten Checkboxen, eingetragenen Domains teils nicht richtig darzustellen. Das liegt vielleicht auch an der Multisite Konfiguration.

Wir haben für unsere OV'en eine Multisite mit knapp 20 Domains umgesetzt, da sind die Rules ganz schön lang. 

Hier mein zusammen gestellter Code für die .htaccess, der ist noch nicht optimal (ich finde ihn sehr unübersichtlich aufgrund der Menge an Domains), aber vielleicht schon mal ein guter Startpunkt.
`
# BEGIN HttpHeaders
#### Alle Änderungen an den Anweisungen zwischen diesen Markierungen werden überschrieben.
<IfModule mod_headers.c>
  Header always set X-Content-Type-Options "nosniff"
  <IfModule mod_setenvif.c>
    SetEnvIf Origin "^()$" CORS=$0
  </IfModule>
  Header set Access-Control-Allow-Origin %{CORS}e env=CORS
  Header append Vary "Origin" env=CORS
  Header set Access-Control-Allow-Credentials "true" env=CORS
  Header set Access-Control-Max-Age "300" env=CORS
  <FilesMatch "\.(php|html)$">
    Header set X-Frame-Options "DENY"
    Header set X-XSS-Protection "1"
    Header set X-Download-Options "noopen"
    Header set X-Permitted-Cross-Domain-Policies "none"
    Header set X-DNS-Prefetch-Control "on"
    Header set Connection "close"
    Header set Age "24"
    Header set Cache-Control "must-revalidate, no-cache, no-store, no-transform, public, private, proxy-revalidate, max-age=604800, s-maxage=604800, immutable, stale-while-revalidate=86400, stale-if-error=86400"
    Header set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" env=HTTPS
    Header set X-UA-Compatible "IE=edge,chrome=1"
    Header set Content-Security-Policy "default-src 'none' filesystem: https://gruene-hasloh.de https://gruene-boenningstedt.de https://gruene-uetersen.de https://gruene-sparrieshoop.de https://gruene-pinneberg.de https://gruene-holm.de https://gruene-halstenbek.de https://gruene-helgoland.de https://gruene-tornesch.de https://gruene-ellerbek.de https://gruene-klein-nordende.de https://gruene-koelln-reisiek.de https://gruene-quickborn.de https://gruene-barmstedt.de https://gruene-moorrege.de https://gruene-pi.de https://gruene-heidgraben.de; img-src 'self' data: http: http://gruene-appen.de http://gruene-hasloh.de http://gruene-boenningstedt.de http://gruene-uetersen.de http://gruene-sparrieshoop.de http://gruene-pinneberg.de http://gruene-holm.de http://gruene-halstenbek.de http://gruene-helgoland.de http://gruene-tornesch.de http://gruene-ellerbek.de http://gruene-klein-nordende.de http://gruene-koelln-reisiek.de http://gruene-quickborn.de http://gruene-barmstedt.de http://gruene-moorrege.de http://gruene-pi.de http://gruene-heidgraben.de https: https://gruene-appen.de https://gruene-hasloh.de https://gruene-boenningstedt.de https://gruene-uetersen.de https://gruene-sparrieshoop.de https://gruene-pinneberg.de https://gruene-holm.de https://gruene-halstenbek.de https://gruene-helgoland.de https://gruene-tornesch.de https://gruene-ellerbek.de https://gruene-klein-nordende.de https://gruene-koelln-reisiek.de https://gruene-quickborn.de https://gruene-barmstedt.de https://gruene-moorrege.de https://gruene-pi.de https://gruene-heidgraben.de; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: https://gruene-hasloh.de https://gruene-boenningstedt.de https://gruene-uetersen.de https://gruene-sparrieshoop.de https://gruene-pinneberg.de https://gruene-holm.de https://gruene-halstenbek.de https://gruene-helgoland.de https://gruene-tornesch.de https://gruene-ellerbek.de https://gruene-klein-nordende.de https://gruene-koelln-reisiek.de https://gruene-quickborn.de https://gruene-barmstedt.de https://gruene-moorrege.de https://gruene-pi.de https://gruene-heidgraben.de; style-src 'self' 'unsafe-inline' https: data: mediastream: blob: filesystem: gruene-hasloh.de gruene-boenningstedt.de gruene-uetersen.de gruene-sparrieshoop.de gruene-pinneberg.de gruene-holm.de gruene-halstenbek.de gruene-helgoland.de gruene-tornesch.de gruene-ellerbek.de gruene-klein-nordende.de gruene-koelln-reisiek.de gruene-quickborn.de gruene-barmstedt.de gruene-moorrege.de gruene-pi.de gruene-heidgraben.de; form-action 'self' *.gruene-hasloh.de *.gruene-boenningstedt.de *.gruene-uetersen.de *.gruene-sparrieshoop.de *.gruene-pinneberg.de *.gruene-holm.de *.gruene-halstenbek.de *.gruene-helgoland.de *.gruene-tornesch.de *.gruene-ellerbek.de *.gruene-klein-nordende.de *.gruene-koelln-reisiek.de *.gruene-quickborn.de *.gruene-barmstedt.de *.gruene-moorrege.de *.gruene-pi.de *.gruene-heidgraben.de; frame-ancestors 'self' *.gruene-hasloh.de *.gruene-boenningstedt.de *.gruene-uetersen.de *.gruene-sparrieshoop.de *.gruene-pinneberg.de *.gruene-holm.de *.gruene-halstenbek.de *.gruene-helgoland.de *.gruene-tornesch.de *.gruene-ellerbek.de *.gruene-klein-nordende.de *.gruene-koelln-reisiek.de *.gruene-quickborn.de *.gruene-barmstedt.de *.gruene-moorrege.de *.gruene-pi.de *.gruene-heidgraben.de; object-src 'self' *.gruene-hasloh.de *.gruene-boenningstedt.de *.gruene-uetersen.de *.gruene-sparrieshoop.de *.gruene-pinneberg.de *.gruene-holm.de *.gruene-halstenbek.de *.gruene-helgoland.de *.gruene-tornesch.de *.gruene-ellerbek.de *.gruene-klein-nordende.de *.gruene-koelln-reisiek.de *.gruene-quickborn.de *.gruene-barmstedt.de *.gruene-moorrege.de *.gruene-pi.de *.gruene-heidgraben.de; frame-src 'self' https: data: mediastream: blob: filesystem: https://spenden.twingle.de; manifest-src 'unsafe-eval'"
    Header set Cross-Origin-Resource-Policy "same-site"
    Header set Cross-Origin-Embedder-Policy "unsafe-none"
    Header set Cross-Origin-Opener-Policy "same-origin"
    Header set Expect-CT 'max-age=31536000, enforce, report-uri="https://gruene-pi.de/wp-content/themes/sunflower-child/report/Expect-CT"'
    Header set Feature-Policy "accelerometer 'self'; ambient-light-sensor 'self'; autoplay 'self'; camera 'self'; cookie 'self'; docwrite 'self'; domain 'self'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; gyroscope 'self'; magnetometer 'self'; microphone 'self'; midi 'self'; payment https://spenden.twingle.de; picture-in-picture 'self'; speaker 'self'; sync-script 'self'; sync-xhr 'self'; unsized-media 'self'; usb 'self'; vertical-scroll 'self'; vibrate 'self'; vr 'self'"
    Header set Permissions-Policy 'accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), interest-cohort=(), layout-animations=(), legacy-image-formats=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), oversized-images=(), payment=("https://spenden.twingle.de"), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-script=(), sync-xhr=(), usb=(), vertical-scroll=(), web-share=(), wake-lock=(), xr-spatial-tracking=()'
    Header append Vary "Accept-Encoding, User-Agent, Referer, Cookie"
  </FilesMatch>
</IfModule>
#### END HttpHeaders

# BEGIN HttpHeadersAuth
<IfModule mod_mime.c>
  AddType application/vnd.ms-fontobject .eot
  AddType image/svg+xml .svg
  AddType application/x-font-ttf .ttf
  AddType application/font-woff .woff
  AddType application/font-woff2 .woff2
  AddType application/javascript .jsonp
</IfModule>
#### END HttpHeadersContentType

# BEGIN HttpHeadersExpires
<IfModule mod_headers.c>
  <FilesMatch "\.(js|css|jpe?g|png|gif|eot|otf|svg|ttf|woff2?)$">
    Header set Timing-Allow-Origin "https://gruene-hasloh.de https://gruene-boenningstedt.de https://gruene-uetersen.de https://gruene-sparrieshoop.de https://gruene-pinneberg.de https://gruene-holm.de https://gruene-halstenbek.de https://gruene-helgoland.de https://gruene-tornesch.de https://gruene-ellerbek.de https://gruene-klein-nordende.de https://gruene-koelln-reisiek.de https://gruene-quickborn.de https://gruene-barmstedt.de https://gruene-moorrege.de https://gruene-pi.de https://gruene-heidgraben.de"
  </FilesMatch>
</IfModule>
#### END HttpHeadersTiming`

**Comment by albig** [comment]
Das ist keine Aufgabe, die das Sunflower-Theme lösen kann. Frag bitte bei deinen Hoster oder auch im [ #wordpress-Kanal der Chatbegrünung](https://chatbegruenung.de/channel/wordpress) nach.
